// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.17.3
// source: pkg/ipc/query.proto

package ipc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateStreamIn struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Target *DomainStream `protobuf:"bytes,1,opt,name=target,proto3" json:"target,omitempty"`
}

func (x *CreateStreamIn) Reset() {
	*x = CreateStreamIn{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_ipc_query_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateStreamIn) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateStreamIn) ProtoMessage() {}

func (x *CreateStreamIn) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_ipc_query_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateStreamIn.ProtoReflect.Descriptor instead.
func (*CreateStreamIn) Descriptor() ([]byte, []int) {
	return file_pkg_ipc_query_proto_rawDescGZIP(), []int{0}
}

func (x *CreateStreamIn) GetTarget() *DomainStream {
	if x != nil {
		return x.Target
	}
	return nil
}

type CreateStreamOut struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Existed bool `protobuf:"varint,1,opt,name=existed,proto3" json:"existed,omitempty"`
}

func (x *CreateStreamOut) Reset() {
	*x = CreateStreamOut{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_ipc_query_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateStreamOut) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateStreamOut) ProtoMessage() {}

func (x *CreateStreamOut) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_ipc_query_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateStreamOut.ProtoReflect.Descriptor instead.
func (*CreateStreamOut) Descriptor() ([]byte, []int) {
	return file_pkg_ipc_query_proto_rawDescGZIP(), []int{1}
}

func (x *CreateStreamOut) GetExisted() bool {
	if x != nil {
		return x.Existed
	}
	return false
}

type ListStreamsIn struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ListStreamsIn) Reset() {
	*x = ListStreamsIn{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_ipc_query_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListStreamsIn) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListStreamsIn) ProtoMessage() {}

func (x *ListStreamsIn) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_ipc_query_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListStreamsIn.ProtoReflect.Descriptor instead.
func (*ListStreamsIn) Descriptor() ([]byte, []int) {
	return file_pkg_ipc_query_proto_rawDescGZIP(), []int{2}
}

type ListStreamsOut struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Target []*DomainStream `protobuf:"bytes,1,rep,name=target,proto3" json:"target,omitempty"`
}

func (x *ListStreamsOut) Reset() {
	*x = ListStreamsOut{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_ipc_query_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListStreamsOut) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListStreamsOut) ProtoMessage() {}

func (x *ListStreamsOut) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_ipc_query_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListStreamsOut.ProtoReflect.Descriptor instead.
func (*ListStreamsOut) Descriptor() ([]byte, []int) {
	return file_pkg_ipc_query_proto_rawDescGZIP(), []int{3}
}

func (x *ListStreamsOut) GetTarget() []*DomainStream {
	if x != nil {
		return x.Target
	}
	return nil
}

type DomainStream struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Domain string `protobuf:"bytes,1,opt,name=domain,proto3" json:"domain,omitempty"`
	Stream string `protobuf:"bytes,2,opt,name=stream,proto3" json:"stream,omitempty"`
}

func (x *DomainStream) Reset() {
	*x = DomainStream{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_ipc_query_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DomainStream) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DomainStream) ProtoMessage() {}

func (x *DomainStream) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_ipc_query_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DomainStream.ProtoReflect.Descriptor instead.
func (*DomainStream) Descriptor() ([]byte, []int) {
	return file_pkg_ipc_query_proto_rawDescGZIP(), []int{4}
}

func (x *DomainStream) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

func (x *DomainStream) GetStream() string {
	if x != nil {
		return x.Stream
	}
	return ""
}

type SubmitIn struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Events       *DomainStream `protobuf:"bytes,1,opt,name=events,proto3" json:"events,omitempty"`
	Kind         string        `protobuf:"bytes,2,opt,name=kind,proto3" json:"kind,omitempty"`
	Body         []byte        `protobuf:"bytes,3,opt,name=body,proto3" json:"body,omitempty"`
	Expectations *Consistency  `protobuf:"bytes,4,opt,name=expectations,proto3,oneof" json:"expectations,omitempty"`
}

func (x *SubmitIn) Reset() {
	*x = SubmitIn{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_ipc_query_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SubmitIn) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitIn) ProtoMessage() {}

func (x *SubmitIn) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_ipc_query_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitIn.ProtoReflect.Descriptor instead.
func (*SubmitIn) Descriptor() ([]byte, []int) {
	return file_pkg_ipc_query_proto_rawDescGZIP(), []int{5}
}

func (x *SubmitIn) GetEvents() *DomainStream {
	if x != nil {
		return x.Events
	}
	return nil
}

func (x *SubmitIn) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *SubmitIn) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *SubmitIn) GetExpectations() *Consistency {
	if x != nil {
		return x.Expectations
	}
	return nil
}

type SubmitOut struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id    int64        `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	State *Consistency `protobuf:"bytes,2,opt,name=state,proto3,oneof" json:"state,omitempty"`
}

func (x *SubmitOut) Reset() {
	*x = SubmitOut{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_ipc_query_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SubmitOut) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitOut) ProtoMessage() {}

func (x *SubmitOut) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_ipc_query_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitOut.ProtoReflect.Descriptor instead.
func (*SubmitOut) Descriptor() ([]byte, []int) {
	return file_pkg_ipc_query_proto_rawDescGZIP(), []int{6}
}

func (x *SubmitOut) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *SubmitOut) GetState() *Consistency {
	if x != nil {
		return x.State
	}
	return nil
}

type GetIn struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Events       *DomainStream `protobuf:"bytes,1,opt,name=events,proto3" json:"events,omitempty"`
	Id           int64         `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	Expectations *Consistency  `protobuf:"bytes,4,opt,name=expectations,proto3,oneof" json:"expectations,omitempty"`
}

func (x *GetIn) Reset() {
	*x = GetIn{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_ipc_query_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetIn) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetIn) ProtoMessage() {}

func (x *GetIn) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_ipc_query_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetIn.ProtoReflect.Descriptor instead.
func (*GetIn) Descriptor() ([]byte, []int) {
	return file_pkg_ipc_query_proto_rawDescGZIP(), []int{7}
}

func (x *GetIn) GetEvents() *DomainStream {
	if x != nil {
		return x.Events
	}
	return nil
}

func (x *GetIn) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GetIn) GetExpectations() *Consistency {
	if x != nil {
		return x.Expectations
	}
	return nil
}

type GetOut struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Envelope *MaterializedEnvelope `protobuf:"bytes,1,opt,name=envelope,proto3" json:"envelope,omitempty"`
	Payload  []byte                `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	State    *Consistency          `protobuf:"bytes,3,opt,name=state,proto3,oneof" json:"state,omitempty"`
}

func (x *GetOut) Reset() {
	*x = GetOut{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_ipc_query_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetOut) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOut) ProtoMessage() {}

func (x *GetOut) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_ipc_query_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOut.ProtoReflect.Descriptor instead.
func (*GetOut) Descriptor() ([]byte, []int) {
	return file_pkg_ipc_query_proto_rawDescGZIP(), []int{8}
}

func (x *GetOut) GetEnvelope() *MaterializedEnvelope {
	if x != nil {
		return x.Envelope
	}
	return nil
}

func (x *GetOut) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *GetOut) GetState() *Consistency {
	if x != nil {
		return x.State
	}
	return nil
}

type Consistency struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// after indicates the last known event
	After int64 `protobuf:"varint,1,opt,name=after,proto3" json:"after,omitempty"`
}

func (x *Consistency) Reset() {
	*x = Consistency{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_ipc_query_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Consistency) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Consistency) ProtoMessage() {}

func (x *Consistency) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_ipc_query_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Consistency.ProtoReflect.Descriptor instead.
func (*Consistency) Descriptor() ([]byte, []int) {
	return file_pkg_ipc_query_proto_rawDescGZIP(), []int{9}
}

func (x *Consistency) GetAfter() int64 {
	if x != nil {
		return x.After
	}
	return 0
}

type MaterializedEnvelope struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id   int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	When *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=when,proto3" json:"when,omitempty"`
	Kind string                 `protobuf:"bytes,3,opt,name=kind,proto3" json:"kind,omitempty"`
}

func (x *MaterializedEnvelope) Reset() {
	*x = MaterializedEnvelope{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_ipc_query_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MaterializedEnvelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MaterializedEnvelope) ProtoMessage() {}

func (x *MaterializedEnvelope) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_ipc_query_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MaterializedEnvelope.ProtoReflect.Descriptor instead.
func (*MaterializedEnvelope) Descriptor() ([]byte, []int) {
	return file_pkg_ipc_query_proto_rawDescGZIP(), []int{10}
}

func (x *MaterializedEnvelope) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *MaterializedEnvelope) GetWhen() *timestamppb.Timestamp {
	if x != nil {
		return x.When
	}
	return nil
}

func (x *MaterializedEnvelope) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

type QueryIn struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Events *DomainStream   `protobuf:"bytes,1,opt,name=events,proto3" json:"events,omitempty"`
	OnKind []*OnKindClause `protobuf:"bytes,2,rep,name=onKind,proto3" json:"onKind,omitempty"`
	OnID   []*OnIDClause   `protobuf:"bytes,3,rep,name=onID,proto3" json:"onID,omitempty"`
	State  *Consistency    `protobuf:"bytes,4,opt,name=state,proto3,oneof" json:"state,omitempty"`
	OnEach *OnEachEvent    `protobuf:"bytes,5,opt,name=onEach,proto3,oneof" json:"onEach,omitempty"`
}

func (x *QueryIn) Reset() {
	*x = QueryIn{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_ipc_query_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QueryIn) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryIn) ProtoMessage() {}

func (x *QueryIn) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_ipc_query_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryIn.ProtoReflect.Descriptor instead.
func (*QueryIn) Descriptor() ([]byte, []int) {
	return file_pkg_ipc_query_proto_rawDescGZIP(), []int{11}
}

func (x *QueryIn) GetEvents() *DomainStream {
	if x != nil {
		return x.Events
	}
	return nil
}

func (x *QueryIn) GetOnKind() []*OnKindClause {
	if x != nil {
		return x.OnKind
	}
	return nil
}

func (x *QueryIn) GetOnID() []*OnIDClause {
	if x != nil {
		return x.OnID
	}
	return nil
}

func (x *QueryIn) GetState() *Consistency {
	if x != nil {
		return x.State
	}
	return nil
}

func (x *QueryIn) GetOnEach() *OnEachEvent {
	if x != nil {
		return x.OnEach
	}
	return nil
}

type OnKindClause struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// kind to match within the stream
	Kind string `protobuf:"bytes,1,opt,name=kind,proto3" json:"kind,omitempty"`
	// allOp will be notified for all documents of kind
	AllOp       *int64               `protobuf:"varint,2,opt,name=allOp,proto3,oneof" json:"allOp,omitempty"`
	AllOpConfig *ResultInclude       `protobuf:"bytes,3,opt,name=allOpConfig,proto3,oneof" json:"allOpConfig,omitempty"`
	Subsets     []*OnKindSubsetMatch `protobuf:"bytes,4,rep,name=subsets,proto3" json:"subsets,omitempty"`
}

func (x *OnKindClause) Reset() {
	*x = OnKindClause{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_ipc_query_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OnKindClause) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OnKindClause) ProtoMessage() {}

func (x *OnKindClause) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_ipc_query_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OnKindClause.ProtoReflect.Descriptor instead.
func (*OnKindClause) Descriptor() ([]byte, []int) {
	return file_pkg_ipc_query_proto_rawDescGZIP(), []int{12}
}

func (x *OnKindClause) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *OnKindClause) GetAllOp() int64 {
	if x != nil && x.AllOp != nil {
		return *x.AllOp
	}
	return 0
}

func (x *OnKindClause) GetAllOpConfig() *ResultInclude {
	if x != nil {
		return x.AllOpConfig
	}
	return nil
}

func (x *OnKindClause) GetSubsets() []*OnKindSubsetMatch {
	if x != nil {
		return x.Subsets
	}
	return nil
}

type OnKindSubsetMatch struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Match []byte         `protobuf:"bytes,1,opt,name=match,proto3" json:"match,omitempty"`
	Op    int64          `protobuf:"varint,2,opt,name=op,proto3" json:"op,omitempty"`
	Style *ResultInclude `protobuf:"bytes,3,opt,name=style,proto3,oneof" json:"style,omitempty"`
}

func (x *OnKindSubsetMatch) Reset() {
	*x = OnKindSubsetMatch{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_ipc_query_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OnKindSubsetMatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OnKindSubsetMatch) ProtoMessage() {}

func (x *OnKindSubsetMatch) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_ipc_query_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OnKindSubsetMatch.ProtoReflect.Descriptor instead.
func (*OnKindSubsetMatch) Descriptor() ([]byte, []int) {
	return file_pkg_ipc_query_proto_rawDescGZIP(), []int{13}
}

func (x *OnKindSubsetMatch) GetMatch() []byte {
	if x != nil {
		return x.Match
	}
	return nil
}

func (x *OnKindSubsetMatch) GetOp() int64 {
	if x != nil {
		return x.Op
	}
	return 0
}

func (x *OnKindSubsetMatch) GetStyle() *ResultInclude {
	if x != nil {
		return x.Style
	}
	return nil
}

type OnIDClause struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id    int64          `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Op    int64          `protobuf:"varint,2,opt,name=op,proto3" json:"op,omitempty"`
	Style *ResultInclude `protobuf:"bytes,3,opt,name=style,proto3,oneof" json:"style,omitempty"`
}

func (x *OnIDClause) Reset() {
	*x = OnIDClause{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_ipc_query_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OnIDClause) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OnIDClause) ProtoMessage() {}

func (x *OnIDClause) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_ipc_query_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OnIDClause.ProtoReflect.Descriptor instead.
func (*OnIDClause) Descriptor() ([]byte, []int) {
	return file_pkg_ipc_query_proto_rawDescGZIP(), []int{14}
}

func (x *OnIDClause) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *OnIDClause) GetOp() int64 {
	if x != nil {
		return x.Op
	}
	return 0
}

func (x *OnIDClause) GetStyle() *ResultInclude {
	if x != nil {
		return x.Style
	}
	return nil
}

type OnEachEvent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Op    int64          `protobuf:"varint,1,opt,name=op,proto3" json:"op,omitempty"`
	Style *ResultInclude `protobuf:"bytes,2,opt,name=style,proto3,oneof" json:"style,omitempty"`
}

func (x *OnEachEvent) Reset() {
	*x = OnEachEvent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_ipc_query_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OnEachEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OnEachEvent) ProtoMessage() {}

func (x *OnEachEvent) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_ipc_query_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OnEachEvent.ProtoReflect.Descriptor instead.
func (*OnEachEvent) Descriptor() ([]byte, []int) {
	return file_pkg_ipc_query_proto_rawDescGZIP(), []int{15}
}

func (x *OnEachEvent) GetOp() int64 {
	if x != nil {
		return x.Op
	}
	return 0
}

func (x *OnEachEvent) GetStyle() *ResultInclude {
	if x != nil {
		return x.Style
	}
	return nil
}

type QueryOut struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Op       int64                 `protobuf:"varint,1,opt,name=op,proto3" json:"op,omitempty"`
	Id       *int64                `protobuf:"varint,2,opt,name=id,proto3,oneof" json:"id,omitempty"`
	Envelope *MaterializedEnvelope `protobuf:"bytes,3,opt,name=envelope,proto3,oneof" json:"envelope,omitempty"`
	Body     []byte                `protobuf:"bytes,4,opt,name=body,proto3,oneof" json:"body,omitempty"`
}

func (x *QueryOut) Reset() {
	*x = QueryOut{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_ipc_query_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QueryOut) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryOut) ProtoMessage() {}

func (x *QueryOut) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_ipc_query_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryOut.ProtoReflect.Descriptor instead.
func (*QueryOut) Descriptor() ([]byte, []int) {
	return file_pkg_ipc_query_proto_rawDescGZIP(), []int{16}
}

func (x *QueryOut) GetOp() int64 {
	if x != nil {
		return x.Op
	}
	return 0
}

func (x *QueryOut) GetId() int64 {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return 0
}

func (x *QueryOut) GetEnvelope() *MaterializedEnvelope {
	if x != nil {
		return x.Envelope
	}
	return nil
}

func (x *QueryOut) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

type ResultInclude struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Envelope *bool `protobuf:"varint,1,opt,name=envelope,proto3,oneof" json:"envelope,omitempty"`
	Body     *bool `protobuf:"varint,2,opt,name=body,proto3,oneof" json:"body,omitempty"`
}

func (x *ResultInclude) Reset() {
	*x = ResultInclude{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_ipc_query_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResultInclude) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResultInclude) ProtoMessage() {}

func (x *ResultInclude) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_ipc_query_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResultInclude.ProtoReflect.Descriptor instead.
func (*ResultInclude) Descriptor() ([]byte, []int) {
	return file_pkg_ipc_query_proto_rawDescGZIP(), []int{17}
}

func (x *ResultInclude) GetEnvelope() bool {
	if x != nil && x.Envelope != nil {
		return *x.Envelope
	}
	return false
}

func (x *ResultInclude) GetBody() bool {
	if x != nil && x.Body != nil {
		return *x.Body
	}
	return false
}

var File_pkg_ipc_query_proto protoreflect.FileDescriptor

var file_pkg_ipc_query_proto_rawDesc = []byte{
	0x0a, 0x13, 0x70, 0x6b, 0x67, 0x2f, 0x69, 0x70, 0x63, 0x2f, 0x71, 0x75, 0x65, 0x72, 0x79, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x03, 0x69, 0x70, 0x63, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67,
	0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65,
	0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x3b, 0x0a, 0x0e, 0x43,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x49, 0x6e, 0x12, 0x29, 0x0a,
	0x06, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e,
	0x69, 0x70, 0x63, 0x2e, 0x44, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d,
	0x52, 0x06, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x22, 0x2b, 0x0a, 0x0f, 0x43, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x4f, 0x75, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x65,
	0x78, 0x69, 0x73, 0x74, 0x65, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x65, 0x78,
	0x69, 0x73, 0x74, 0x65, 0x64, 0x22, 0x0f, 0x0a, 0x0d, 0x4c, 0x69, 0x73, 0x74, 0x53, 0x74, 0x72,
	0x65, 0x61, 0x6d, 0x73, 0x49, 0x6e, 0x22, 0x3b, 0x0a, 0x0e, 0x4c, 0x69, 0x73, 0x74, 0x53, 0x74,
	0x72, 0x65, 0x61, 0x6d, 0x73, 0x4f, 0x75, 0x74, 0x12, 0x29, 0x0a, 0x06, 0x74, 0x61, 0x72, 0x67,
	0x65, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x69, 0x70, 0x63, 0x2e, 0x44,
	0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x52, 0x06, 0x74, 0x61, 0x72,
	0x67, 0x65, 0x74, 0x22, 0x3e, 0x0a, 0x0c, 0x44, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x53, 0x74, 0x72,
	0x65, 0x61, 0x6d, 0x12, 0x16, 0x0a, 0x06, 0x64, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x64, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x12, 0x16, 0x0a, 0x06, 0x73,
	0x74, 0x72, 0x65, 0x61, 0x6d, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x74, 0x72,
	0x65, 0x61, 0x6d, 0x22, 0xa9, 0x01, 0x0a, 0x08, 0x53, 0x75, 0x62, 0x6d, 0x69, 0x74, 0x49, 0x6e,
	0x12, 0x29, 0x0a, 0x06, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x11, 0x2e, 0x69, 0x70, 0x63, 0x2e, 0x44, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x53, 0x74, 0x72,
	0x65, 0x61, 0x6d, 0x52, 0x06, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x6b,
	0x69, 0x6e, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6b, 0x69, 0x6e, 0x64, 0x12,
	0x12, 0x0a, 0x04, 0x62, 0x6f, 0x64, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x62,
	0x6f, 0x64, 0x79, 0x12, 0x39, 0x0a, 0x0c, 0x65, 0x78, 0x70, 0x65, 0x63, 0x74, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x69, 0x70, 0x63, 0x2e,
	0x43, 0x6f, 0x6e, 0x73, 0x69, 0x73, 0x74, 0x65, 0x6e, 0x63, 0x79, 0x48, 0x00, 0x52, 0x0c, 0x65,
	0x78, 0x70, 0x65, 0x63, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x88, 0x01, 0x01, 0x42, 0x0f,
	0x0a, 0x0d, 0x5f, 0x65, 0x78, 0x70, 0x65, 0x63, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x22,
	0x52, 0x0a, 0x09, 0x53, 0x75, 0x62, 0x6d, 0x69, 0x74, 0x4f, 0x75, 0x74, 0x12, 0x0e, 0x0a, 0x02,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x2b, 0x0a, 0x05,
	0x73, 0x74, 0x61, 0x74, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x69, 0x70,
	0x63, 0x2e, 0x43, 0x6f, 0x6e, 0x73, 0x69, 0x73, 0x74, 0x65, 0x6e, 0x63, 0x79, 0x48, 0x00, 0x52,
	0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x88, 0x01, 0x01, 0x42, 0x08, 0x0a, 0x06, 0x5f, 0x73, 0x74,
	0x61, 0x74, 0x65, 0x22, 0x8e, 0x01, 0x0a, 0x05, 0x47, 0x65, 0x74, 0x49, 0x6e, 0x12, 0x29, 0x0a,
	0x06, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e,
	0x69, 0x70, 0x63, 0x2e, 0x44, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d,
	0x52, 0x06, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x39, 0x0a, 0x0c, 0x65, 0x78, 0x70, 0x65,
	0x63, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10,
	0x2e, 0x69, 0x70, 0x63, 0x2e, 0x43, 0x6f, 0x6e, 0x73, 0x69, 0x73, 0x74, 0x65, 0x6e, 0x63, 0x79,
	0x48, 0x00, 0x52, 0x0c, 0x65, 0x78, 0x70, 0x65, 0x63, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73,
	0x88, 0x01, 0x01, 0x42, 0x0f, 0x0a, 0x0d, 0x5f, 0x65, 0x78, 0x70, 0x65, 0x63, 0x74, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x73, 0x22, 0x90, 0x01, 0x0a, 0x06, 0x47, 0x65, 0x74, 0x4f, 0x75, 0x74, 0x12,
	0x35, 0x0a, 0x08, 0x65, 0x6e, 0x76, 0x65, 0x6c, 0x6f, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x19, 0x2e, 0x69, 0x70, 0x63, 0x2e, 0x4d, 0x61, 0x74, 0x65, 0x72, 0x69, 0x61, 0x6c,
	0x69, 0x7a, 0x65, 0x64, 0x45, 0x6e, 0x76, 0x65, 0x6c, 0x6f, 0x70, 0x65, 0x52, 0x08, 0x65, 0x6e,
	0x76, 0x65, 0x6c, 0x6f, 0x70, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61,
	0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64,
	0x12, 0x2b, 0x0a, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x10, 0x2e, 0x69, 0x70, 0x63, 0x2e, 0x43, 0x6f, 0x6e, 0x73, 0x69, 0x73, 0x74, 0x65, 0x6e, 0x63,
	0x79, 0x48, 0x00, 0x52, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x88, 0x01, 0x01, 0x42, 0x08, 0x0a,
	0x06, 0x5f, 0x73, 0x74, 0x61, 0x74, 0x65, 0x22, 0x23, 0x0a, 0x0b, 0x43, 0x6f, 0x6e, 0x73, 0x69,
	0x73, 0x74, 0x65, 0x6e, 0x63, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x61, 0x66, 0x74, 0x65, 0x72, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x61, 0x66, 0x74, 0x65, 0x72, 0x22, 0x6a, 0x0a, 0x14,
	0x4d, 0x61, 0x74, 0x65, 0x72, 0x69, 0x61, 0x6c, 0x69, 0x7a, 0x65, 0x64, 0x45, 0x6e, 0x76, 0x65,
	0x6c, 0x6f, 0x70, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x02, 0x69, 0x64, 0x12, 0x2e, 0x0a, 0x04, 0x77, 0x68, 0x65, 0x6e, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x04,
	0x77, 0x68, 0x65, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x6b, 0x69, 0x6e, 0x64, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x6b, 0x69, 0x6e, 0x64, 0x22, 0xf5, 0x01, 0x0a, 0x07, 0x51, 0x75, 0x65,
	0x72, 0x79, 0x49, 0x6e, 0x12, 0x29, 0x0a, 0x06, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x69, 0x70, 0x63, 0x2e, 0x44, 0x6f, 0x6d, 0x61, 0x69,
	0x6e, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x52, 0x06, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x12,
	0x29, 0x0a, 0x06, 0x6f, 0x6e, 0x4b, 0x69, 0x6e, 0x64, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x11, 0x2e, 0x69, 0x70, 0x63, 0x2e, 0x4f, 0x6e, 0x4b, 0x69, 0x6e, 0x64, 0x43, 0x6c, 0x61, 0x75,
	0x73, 0x65, 0x52, 0x06, 0x6f, 0x6e, 0x4b, 0x69, 0x6e, 0x64, 0x12, 0x23, 0x0a, 0x04, 0x6f, 0x6e,
	0x49, 0x44, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x69, 0x70, 0x63, 0x2e, 0x4f,
	0x6e, 0x49, 0x44, 0x43, 0x6c, 0x61, 0x75, 0x73, 0x65, 0x52, 0x04, 0x6f, 0x6e, 0x49, 0x44, 0x12,
	0x2b, 0x0a, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10,
	0x2e, 0x69, 0x70, 0x63, 0x2e, 0x43, 0x6f, 0x6e, 0x73, 0x69, 0x73, 0x74, 0x65, 0x6e, 0x63, 0x79,
	0x48, 0x00, 0x52, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x88, 0x01, 0x01, 0x12, 0x2d, 0x0a, 0x06,
	0x6f, 0x6e, 0x45, 0x61, 0x63, 0x68, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x69,
	0x70, 0x63, 0x2e, 0x4f, 0x6e, 0x45, 0x61, 0x63, 0x68, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x48, 0x01,
	0x52, 0x06, 0x6f, 0x6e, 0x45, 0x61, 0x63, 0x68, 0x88, 0x01, 0x01, 0x42, 0x08, 0x0a, 0x06, 0x5f,
	0x73, 0x74, 0x61, 0x74, 0x65, 0x42, 0x09, 0x0a, 0x07, 0x5f, 0x6f, 0x6e, 0x45, 0x61, 0x63, 0x68,
	0x22, 0xc4, 0x01, 0x0a, 0x0c, 0x4f, 0x6e, 0x4b, 0x69, 0x6e, 0x64, 0x43, 0x6c, 0x61, 0x75, 0x73,
	0x65, 0x12, 0x12, 0x0a, 0x04, 0x6b, 0x69, 0x6e, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x6b, 0x69, 0x6e, 0x64, 0x12, 0x19, 0x0a, 0x05, 0x61, 0x6c, 0x6c, 0x4f, 0x70, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x03, 0x48, 0x00, 0x52, 0x05, 0x61, 0x6c, 0x6c, 0x4f, 0x70, 0x88, 0x01, 0x01,
	0x12, 0x39, 0x0a, 0x0b, 0x61, 0x6c, 0x6c, 0x4f, 0x70, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x69, 0x70, 0x63, 0x2e, 0x52, 0x65, 0x73, 0x75,
	0x6c, 0x74, 0x49, 0x6e, 0x63, 0x6c, 0x75, 0x64, 0x65, 0x48, 0x01, 0x52, 0x0b, 0x61, 0x6c, 0x6c,
	0x4f, 0x70, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x88, 0x01, 0x01, 0x12, 0x30, 0x0a, 0x07, 0x73,
	0x75, 0x62, 0x73, 0x65, 0x74, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x69,
	0x70, 0x63, 0x2e, 0x4f, 0x6e, 0x4b, 0x69, 0x6e, 0x64, 0x53, 0x75, 0x62, 0x73, 0x65, 0x74, 0x4d,
	0x61, 0x74, 0x63, 0x68, 0x52, 0x07, 0x73, 0x75, 0x62, 0x73, 0x65, 0x74, 0x73, 0x42, 0x08, 0x0a,
	0x06, 0x5f, 0x61, 0x6c, 0x6c, 0x4f, 0x70, 0x42, 0x0e, 0x0a, 0x0c, 0x5f, 0x61, 0x6c, 0x6c, 0x4f,
	0x70, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x22, 0x72, 0x0a, 0x11, 0x4f, 0x6e, 0x4b, 0x69, 0x6e,
	0x64, 0x53, 0x75, 0x62, 0x73, 0x65, 0x74, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x12, 0x14, 0x0a, 0x05,
	0x6d, 0x61, 0x74, 0x63, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05, 0x6d, 0x61, 0x74,
	0x63, 0x68, 0x12, 0x0e, 0x0a, 0x02, 0x6f, 0x70, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02,
	0x6f, 0x70, 0x12, 0x2d, 0x0a, 0x05, 0x73, 0x74, 0x79, 0x6c, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x12, 0x2e, 0x69, 0x70, 0x63, 0x2e, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x49, 0x6e,
	0x63, 0x6c, 0x75, 0x64, 0x65, 0x48, 0x00, 0x52, 0x05, 0x73, 0x74, 0x79, 0x6c, 0x65, 0x88, 0x01,
	0x01, 0x42, 0x08, 0x0a, 0x06, 0x5f, 0x73, 0x74, 0x79, 0x6c, 0x65, 0x22, 0x65, 0x0a, 0x0a, 0x4f,
	0x6e, 0x49, 0x44, 0x43, 0x6c, 0x61, 0x75, 0x73, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x0e, 0x0a, 0x02, 0x6f, 0x70, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x6f, 0x70, 0x12, 0x2d, 0x0a, 0x05, 0x73, 0x74, 0x79,
	0x6c, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x69, 0x70, 0x63, 0x2e, 0x52,
	0x65, 0x73, 0x75, 0x6c, 0x74, 0x49, 0x6e, 0x63, 0x6c, 0x75, 0x64, 0x65, 0x48, 0x00, 0x52, 0x05,
	0x73, 0x74, 0x79, 0x6c, 0x65, 0x88, 0x01, 0x01, 0x42, 0x08, 0x0a, 0x06, 0x5f, 0x73, 0x74, 0x79,
	0x6c, 0x65, 0x22, 0x56, 0x0a, 0x0b, 0x4f, 0x6e, 0x45, 0x61, 0x63, 0x68, 0x45, 0x76, 0x65, 0x6e,
	0x74, 0x12, 0x0e, 0x0a, 0x02, 0x6f, 0x70, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x6f,
	0x70, 0x12, 0x2d, 0x0a, 0x05, 0x73, 0x74, 0x79, 0x6c, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x12, 0x2e, 0x69, 0x70, 0x63, 0x2e, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x49, 0x6e, 0x63,
	0x6c, 0x75, 0x64, 0x65, 0x48, 0x00, 0x52, 0x05, 0x73, 0x74, 0x79, 0x6c, 0x65, 0x88, 0x01, 0x01,
	0x42, 0x08, 0x0a, 0x06, 0x5f, 0x73, 0x74, 0x79, 0x6c, 0x65, 0x22, 0xa1, 0x01, 0x0a, 0x08, 0x51,
	0x75, 0x65, 0x72, 0x79, 0x4f, 0x75, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x6f, 0x70, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x02, 0x6f, 0x70, 0x12, 0x13, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x03, 0x48, 0x00, 0x52, 0x02, 0x69, 0x64, 0x88, 0x01, 0x01, 0x12, 0x3a, 0x0a, 0x08,
	0x65, 0x6e, 0x76, 0x65, 0x6c, 0x6f, 0x70, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19,
	0x2e, 0x69, 0x70, 0x63, 0x2e, 0x4d, 0x61, 0x74, 0x65, 0x72, 0x69, 0x61, 0x6c, 0x69, 0x7a, 0x65,
	0x64, 0x45, 0x6e, 0x76, 0x65, 0x6c, 0x6f, 0x70, 0x65, 0x48, 0x01, 0x52, 0x08, 0x65, 0x6e, 0x76,
	0x65, 0x6c, 0x6f, 0x70, 0x65, 0x88, 0x01, 0x01, 0x12, 0x17, 0x0a, 0x04, 0x62, 0x6f, 0x64, 0x79,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x0c, 0x48, 0x02, 0x52, 0x04, 0x62, 0x6f, 0x64, 0x79, 0x88, 0x01,
	0x01, 0x42, 0x05, 0x0a, 0x03, 0x5f, 0x69, 0x64, 0x42, 0x0b, 0x0a, 0x09, 0x5f, 0x65, 0x6e, 0x76,
	0x65, 0x6c, 0x6f, 0x70, 0x65, 0x42, 0x07, 0x0a, 0x05, 0x5f, 0x62, 0x6f, 0x64, 0x79, 0x22, 0x5f,
	0x0a, 0x0d, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x49, 0x6e, 0x63, 0x6c, 0x75, 0x64, 0x65, 0x12,
	0x1f, 0x0a, 0x08, 0x65, 0x6e, 0x76, 0x65, 0x6c, 0x6f, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x08, 0x48, 0x00, 0x52, 0x08, 0x65, 0x6e, 0x76, 0x65, 0x6c, 0x6f, 0x70, 0x65, 0x88, 0x01, 0x01,
	0x12, 0x17, 0x0a, 0x04, 0x62, 0x6f, 0x64, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x48, 0x01,
	0x52, 0x04, 0x62, 0x6f, 0x64, 0x79, 0x88, 0x01, 0x01, 0x42, 0x0b, 0x0a, 0x09, 0x5f, 0x65, 0x6e,
	0x76, 0x65, 0x6c, 0x6f, 0x70, 0x65, 0x42, 0x07, 0x0a, 0x05, 0x5f, 0x62, 0x6f, 0x64, 0x79, 0x32,
	0x6d, 0x0a, 0x07, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x12, 0x39, 0x0a, 0x0c, 0x43, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x12, 0x13, 0x2e, 0x69, 0x70, 0x63,
	0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x49, 0x6e, 0x1a,
	0x14, 0x2e, 0x69, 0x70, 0x63, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x53, 0x74, 0x72, 0x65,
	0x61, 0x6d, 0x4f, 0x75, 0x74, 0x12, 0x27, 0x0a, 0x06, 0x53, 0x75, 0x62, 0x6d, 0x69, 0x74, 0x12,
	0x0d, 0x2e, 0x69, 0x70, 0x63, 0x2e, 0x53, 0x75, 0x62, 0x6d, 0x69, 0x74, 0x49, 0x6e, 0x1a, 0x0e,
	0x2e, 0x69, 0x70, 0x63, 0x2e, 0x53, 0x75, 0x62, 0x6d, 0x69, 0x74, 0x4f, 0x75, 0x74, 0x32, 0x87,
	0x01, 0x0a, 0x05, 0x51, 0x75, 0x65, 0x72, 0x79, 0x12, 0x36, 0x0a, 0x0b, 0x4c, 0x69, 0x73, 0x74,
	0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x73, 0x12, 0x12, 0x2e, 0x69, 0x70, 0x63, 0x2e, 0x4c, 0x69,
	0x73, 0x74, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x73, 0x49, 0x6e, 0x1a, 0x13, 0x2e, 0x69, 0x70,
	0x63, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x73, 0x4f, 0x75, 0x74,
	0x12, 0x1e, 0x0a, 0x03, 0x47, 0x65, 0x74, 0x12, 0x0a, 0x2e, 0x69, 0x70, 0x63, 0x2e, 0x47, 0x65,
	0x74, 0x49, 0x6e, 0x1a, 0x0b, 0x2e, 0x69, 0x70, 0x63, 0x2e, 0x47, 0x65, 0x74, 0x4f, 0x75, 0x74,
	0x12, 0x26, 0x0a, 0x05, 0x51, 0x75, 0x65, 0x72, 0x79, 0x12, 0x0c, 0x2e, 0x69, 0x70, 0x63, 0x2e,
	0x51, 0x75, 0x65, 0x72, 0x79, 0x49, 0x6e, 0x1a, 0x0d, 0x2e, 0x69, 0x70, 0x63, 0x2e, 0x51, 0x75,
	0x65, 0x72, 0x79, 0x4f, 0x75, 0x74, 0x30, 0x01, 0x42, 0x09, 0x5a, 0x07, 0x70, 0x6b, 0x67, 0x2f,
	0x69, 0x70, 0x63, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pkg_ipc_query_proto_rawDescOnce sync.Once
	file_pkg_ipc_query_proto_rawDescData = file_pkg_ipc_query_proto_rawDesc
)

func file_pkg_ipc_query_proto_rawDescGZIP() []byte {
	file_pkg_ipc_query_proto_rawDescOnce.Do(func() {
		file_pkg_ipc_query_proto_rawDescData = protoimpl.X.CompressGZIP(file_pkg_ipc_query_proto_rawDescData)
	})
	return file_pkg_ipc_query_proto_rawDescData
}

var file_pkg_ipc_query_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_pkg_ipc_query_proto_goTypes = []interface{}{
	(*CreateStreamIn)(nil),        // 0: ipc.CreateStreamIn
	(*CreateStreamOut)(nil),       // 1: ipc.CreateStreamOut
	(*ListStreamsIn)(nil),         // 2: ipc.ListStreamsIn
	(*ListStreamsOut)(nil),        // 3: ipc.ListStreamsOut
	(*DomainStream)(nil),          // 4: ipc.DomainStream
	(*SubmitIn)(nil),              // 5: ipc.SubmitIn
	(*SubmitOut)(nil),             // 6: ipc.SubmitOut
	(*GetIn)(nil),                 // 7: ipc.GetIn
	(*GetOut)(nil),                // 8: ipc.GetOut
	(*Consistency)(nil),           // 9: ipc.Consistency
	(*MaterializedEnvelope)(nil),  // 10: ipc.MaterializedEnvelope
	(*QueryIn)(nil),               // 11: ipc.QueryIn
	(*OnKindClause)(nil),          // 12: ipc.OnKindClause
	(*OnKindSubsetMatch)(nil),     // 13: ipc.OnKindSubsetMatch
	(*OnIDClause)(nil),            // 14: ipc.OnIDClause
	(*OnEachEvent)(nil),           // 15: ipc.OnEachEvent
	(*QueryOut)(nil),              // 16: ipc.QueryOut
	(*ResultInclude)(nil),         // 17: ipc.ResultInclude
	(*timestamppb.Timestamp)(nil), // 18: google.protobuf.Timestamp
}
var file_pkg_ipc_query_proto_depIdxs = []int32{
	4,  // 0: ipc.CreateStreamIn.target:type_name -> ipc.DomainStream
	4,  // 1: ipc.ListStreamsOut.target:type_name -> ipc.DomainStream
	4,  // 2: ipc.SubmitIn.events:type_name -> ipc.DomainStream
	9,  // 3: ipc.SubmitIn.expectations:type_name -> ipc.Consistency
	9,  // 4: ipc.SubmitOut.state:type_name -> ipc.Consistency
	4,  // 5: ipc.GetIn.events:type_name -> ipc.DomainStream
	9,  // 6: ipc.GetIn.expectations:type_name -> ipc.Consistency
	10, // 7: ipc.GetOut.envelope:type_name -> ipc.MaterializedEnvelope
	9,  // 8: ipc.GetOut.state:type_name -> ipc.Consistency
	18, // 9: ipc.MaterializedEnvelope.when:type_name -> google.protobuf.Timestamp
	4,  // 10: ipc.QueryIn.events:type_name -> ipc.DomainStream
	12, // 11: ipc.QueryIn.onKind:type_name -> ipc.OnKindClause
	14, // 12: ipc.QueryIn.onID:type_name -> ipc.OnIDClause
	9,  // 13: ipc.QueryIn.state:type_name -> ipc.Consistency
	15, // 14: ipc.QueryIn.onEach:type_name -> ipc.OnEachEvent
	17, // 15: ipc.OnKindClause.allOpConfig:type_name -> ipc.ResultInclude
	13, // 16: ipc.OnKindClause.subsets:type_name -> ipc.OnKindSubsetMatch
	17, // 17: ipc.OnKindSubsetMatch.style:type_name -> ipc.ResultInclude
	17, // 18: ipc.OnIDClause.style:type_name -> ipc.ResultInclude
	17, // 19: ipc.OnEachEvent.style:type_name -> ipc.ResultInclude
	10, // 20: ipc.QueryOut.envelope:type_name -> ipc.MaterializedEnvelope
	0,  // 21: ipc.Command.CreateStream:input_type -> ipc.CreateStreamIn
	5,  // 22: ipc.Command.Submit:input_type -> ipc.SubmitIn
	2,  // 23: ipc.Query.ListStreams:input_type -> ipc.ListStreamsIn
	7,  // 24: ipc.Query.Get:input_type -> ipc.GetIn
	11, // 25: ipc.Query.Query:input_type -> ipc.QueryIn
	1,  // 26: ipc.Command.CreateStream:output_type -> ipc.CreateStreamOut
	6,  // 27: ipc.Command.Submit:output_type -> ipc.SubmitOut
	3,  // 28: ipc.Query.ListStreams:output_type -> ipc.ListStreamsOut
	8,  // 29: ipc.Query.Get:output_type -> ipc.GetOut
	16, // 30: ipc.Query.Query:output_type -> ipc.QueryOut
	26, // [26:31] is the sub-list for method output_type
	21, // [21:26] is the sub-list for method input_type
	21, // [21:21] is the sub-list for extension type_name
	21, // [21:21] is the sub-list for extension extendee
	0,  // [0:21] is the sub-list for field type_name
}

func init() { file_pkg_ipc_query_proto_init() }
func file_pkg_ipc_query_proto_init() {
	if File_pkg_ipc_query_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pkg_ipc_query_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateStreamIn); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_ipc_query_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateStreamOut); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_ipc_query_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListStreamsIn); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_ipc_query_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListStreamsOut); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_ipc_query_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DomainStream); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_ipc_query_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SubmitIn); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_ipc_query_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SubmitOut); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_ipc_query_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetIn); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_ipc_query_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetOut); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_ipc_query_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Consistency); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_ipc_query_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MaterializedEnvelope); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_ipc_query_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QueryIn); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_ipc_query_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OnKindClause); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_ipc_query_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OnKindSubsetMatch); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_ipc_query_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OnIDClause); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_ipc_query_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OnEachEvent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_ipc_query_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QueryOut); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_ipc_query_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResultInclude); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_pkg_ipc_query_proto_msgTypes[5].OneofWrappers = []interface{}{}
	file_pkg_ipc_query_proto_msgTypes[6].OneofWrappers = []interface{}{}
	file_pkg_ipc_query_proto_msgTypes[7].OneofWrappers = []interface{}{}
	file_pkg_ipc_query_proto_msgTypes[8].OneofWrappers = []interface{}{}
	file_pkg_ipc_query_proto_msgTypes[11].OneofWrappers = []interface{}{}
	file_pkg_ipc_query_proto_msgTypes[12].OneofWrappers = []interface{}{}
	file_pkg_ipc_query_proto_msgTypes[13].OneofWrappers = []interface{}{}
	file_pkg_ipc_query_proto_msgTypes[14].OneofWrappers = []interface{}{}
	file_pkg_ipc_query_proto_msgTypes[15].OneofWrappers = []interface{}{}
	file_pkg_ipc_query_proto_msgTypes[16].OneofWrappers = []interface{}{}
	file_pkg_ipc_query_proto_msgTypes[17].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pkg_ipc_query_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_pkg_ipc_query_proto_goTypes,
		DependencyIndexes: file_pkg_ipc_query_proto_depIdxs,
		MessageInfos:      file_pkg_ipc_query_proto_msgTypes,
	}.Build()
	File_pkg_ipc_query_proto = out.File
	file_pkg_ipc_query_proto_rawDesc = nil
	file_pkg_ipc_query_proto_goTypes = nil
	file_pkg_ipc_query_proto_depIdxs = nil
}
