// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: pkg/ipc/query.proto

package ipc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// LockStatusReason describes the outcome of a lock operation.
type LockStatusReason int32

const (
	LockStatusReason_UNSPECIFIED LockStatusReason = 0
	LockStatusReason_RENEWED     LockStatusReason = 1
	LockStatusReason_EXPIRED     LockStatusReason = 2
	LockStatusReason_STOLEN      LockStatusReason = 3
	LockStatusReason_CONFLICT    LockStatusReason = 4
)

// Enum value maps for LockStatusReason.
var (
	LockStatusReason_name = map[int32]string{
		0: "UNSPECIFIED",
		1: "RENEWED",
		2: "EXPIRED",
		3: "STOLEN",
		4: "CONFLICT",
	}
	LockStatusReason_value = map[string]int32{
		"UNSPECIFIED": 0,
		"RENEWED":     1,
		"EXPIRED":     2,
		"STOLEN":      3,
		"CONFLICT":    4,
	}
)

func (x LockStatusReason) Enum() *LockStatusReason {
	p := new(LockStatusReason)
	*p = x
	return p
}

func (x LockStatusReason) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LockStatusReason) Descriptor() protoreflect.EnumDescriptor {
	return file_pkg_ipc_query_proto_enumTypes[0].Descriptor()
}

func (LockStatusReason) Type() protoreflect.EnumType {
	return &file_pkg_ipc_query_proto_enumTypes[0]
}

func (x LockStatusReason) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LockStatusReason.Descriptor instead.
func (LockStatusReason) EnumDescriptor() ([]byte, []int) {
	return file_pkg_ipc_query_proto_rawDescGZIP(), []int{0}
}

type CreateStreamIn struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Target        *DomainStream          `protobuf:"bytes,1,opt,name=target,proto3" json:"target,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateStreamIn) Reset() {
	*x = CreateStreamIn{}
	mi := &file_pkg_ipc_query_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateStreamIn) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateStreamIn) ProtoMessage() {}

func (x *CreateStreamIn) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_ipc_query_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateStreamIn.ProtoReflect.Descriptor instead.
func (*CreateStreamIn) Descriptor() ([]byte, []int) {
	return file_pkg_ipc_query_proto_rawDescGZIP(), []int{0}
}

func (x *CreateStreamIn) GetTarget() *DomainStream {
	if x != nil {
		return x.Target
	}
	return nil
}

type CreateStreamOut struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Existed       bool                   `protobuf:"varint,1,opt,name=existed,proto3" json:"existed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateStreamOut) Reset() {
	*x = CreateStreamOut{}
	mi := &file_pkg_ipc_query_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateStreamOut) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateStreamOut) ProtoMessage() {}

func (x *CreateStreamOut) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_ipc_query_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateStreamOut.ProtoReflect.Descriptor instead.
func (*CreateStreamOut) Descriptor() ([]byte, []int) {
	return file_pkg_ipc_query_proto_rawDescGZIP(), []int{1}
}

func (x *CreateStreamOut) GetExisted() bool {
	if x != nil {
		return x.Existed
	}
	return false
}

type ListStreamsIn struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListStreamsIn) Reset() {
	*x = ListStreamsIn{}
	mi := &file_pkg_ipc_query_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListStreamsIn) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListStreamsIn) ProtoMessage() {}

func (x *ListStreamsIn) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_ipc_query_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListStreamsIn.ProtoReflect.Descriptor instead.
func (*ListStreamsIn) Descriptor() ([]byte, []int) {
	return file_pkg_ipc_query_proto_rawDescGZIP(), []int{2}
}

type ListStreamsOut struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Target        []*DomainStream        `protobuf:"bytes,1,rep,name=target,proto3" json:"target,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListStreamsOut) Reset() {
	*x = ListStreamsOut{}
	mi := &file_pkg_ipc_query_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListStreamsOut) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListStreamsOut) ProtoMessage() {}

func (x *ListStreamsOut) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_ipc_query_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListStreamsOut.ProtoReflect.Descriptor instead.
func (*ListStreamsOut) Descriptor() ([]byte, []int) {
	return file_pkg_ipc_query_proto_rawDescGZIP(), []int{3}
}

func (x *ListStreamsOut) GetTarget() []*DomainStream {
	if x != nil {
		return x.Target
	}
	return nil
}

// *
// DomainStream is the named stream from which to perform operations.
type DomainStream struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// *
	// domain is a grouping of streams
	Domain string `protobuf:"bytes,1,opt,name=domain,proto3" json:"domain,omitempty"`
	// *
	// stream is a specific sequence of related events
	Stream        string `protobuf:"bytes,2,opt,name=stream,proto3" json:"stream,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DomainStream) Reset() {
	*x = DomainStream{}
	mi := &file_pkg_ipc_query_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DomainStream) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DomainStream) ProtoMessage() {}

func (x *DomainStream) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_ipc_query_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DomainStream.ProtoReflect.Descriptor instead.
func (*DomainStream) Descriptor() ([]byte, []int) {
	return file_pkg_ipc_query_proto_rawDescGZIP(), []int{4}
}

func (x *DomainStream) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

func (x *DomainStream) GetStream() string {
	if x != nil {
		return x.Stream
	}
	return ""
}

type SubmitIn struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// events is the particular streams
	Events *DomainStream `protobuf:"bytes,1,opt,name=events,proto3" json:"events,omitempty"`
	// kind is the event type.  useful for filtering or knowing how to interpret the contents.
	Kind string `protobuf:"bytes,2,opt,name=kind,proto3" json:"kind,omitempty"`
	// JSON encoded body of the event in question.
	Body []byte `protobuf:"bytes,3,opt,name=body,proto3" json:"body,omitempty"`
	// expectations are not currently used.
	Expectations *Consistency `protobuf:"bytes,4,opt,name=expectations,proto3,oneof" json:"expectations,omitempty"`
	// lock optionally asserts that the caller holds the specified lock.
	Lock          *Lock `protobuf:"bytes,5,opt,name=lock,proto3,oneof" json:"lock,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitIn) Reset() {
	*x = SubmitIn{}
	mi := &file_pkg_ipc_query_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitIn) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitIn) ProtoMessage() {}

func (x *SubmitIn) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_ipc_query_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitIn.ProtoReflect.Descriptor instead.
func (*SubmitIn) Descriptor() ([]byte, []int) {
	return file_pkg_ipc_query_proto_rawDescGZIP(), []int{5}
}

func (x *SubmitIn) GetEvents() *DomainStream {
	if x != nil {
		return x.Events
	}
	return nil
}

func (x *SubmitIn) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *SubmitIn) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *SubmitIn) GetExpectations() *Consistency {
	if x != nil {
		return x.Expectations
	}
	return nil
}

func (x *SubmitIn) GetLock() *Lock {
	if x != nil {
		return x.Lock
	}
	return nil
}

type SubmitOut struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// id is the event ID to be referred to
	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// state, when set, provides a momento for ensuring the object exists
	State         *Consistency `protobuf:"bytes,2,opt,name=state,proto3,oneof" json:"state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitOut) Reset() {
	*x = SubmitOut{}
	mi := &file_pkg_ipc_query_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitOut) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitOut) ProtoMessage() {}

func (x *SubmitOut) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_ipc_query_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitOut.ProtoReflect.Descriptor instead.
func (*SubmitOut) Descriptor() ([]byte, []int) {
	return file_pkg_ipc_query_proto_rawDescGZIP(), []int{6}
}

func (x *SubmitOut) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *SubmitOut) GetState() *Consistency {
	if x != nil {
		return x.State
	}
	return nil
}

// *
// GetIn describes the retrieval of a specific event.
type GetIn struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// events describes the expected domain and stream this event must be attached to.
	Events *DomainStream `protobuf:"bytes,1,opt,name=events,proto3" json:"events,omitempty"`
	// id is the event stream ID for the specific targeted event.
	Id int64 `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	// expectations describes how the event should be returned to the client.
	Expectations  *Consistency `protobuf:"bytes,4,opt,name=expectations,proto3,oneof" json:"expectations,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetIn) Reset() {
	*x = GetIn{}
	mi := &file_pkg_ipc_query_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetIn) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetIn) ProtoMessage() {}

func (x *GetIn) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_ipc_query_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetIn.ProtoReflect.Descriptor instead.
func (*GetIn) Descriptor() ([]byte, []int) {
	return file_pkg_ipc_query_proto_rawDescGZIP(), []int{7}
}

func (x *GetIn) GetEvents() *DomainStream {
	if x != nil {
		return x.Events
	}
	return nil
}

func (x *GetIn) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GetIn) GetExpectations() *Consistency {
	if x != nil {
		return x.Expectations
	}
	return nil
}

// *
// GetOut describes the results of a GetIn.
type GetOut struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// *
	// envelope describes the event metadata
	Envelope *MaterializedEnvelope `protobuf:"bytes,1,opt,name=envelope,proto3" json:"envelope,omitempty"`
	// *
	// payload is a JSON encoded body of the event
	Payload []byte `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	// *
	// state contains the latest modification state for this event.
	State         *Consistency `protobuf:"bytes,3,opt,name=state,proto3,oneof" json:"state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOut) Reset() {
	*x = GetOut{}
	mi := &file_pkg_ipc_query_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOut) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOut) ProtoMessage() {}

func (x *GetOut) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_ipc_query_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOut.ProtoReflect.Descriptor instead.
func (*GetOut) Descriptor() ([]byte, []int) {
	return file_pkg_ipc_query_proto_rawDescGZIP(), []int{8}
}

func (x *GetOut) GetEnvelope() *MaterializedEnvelope {
	if x != nil {
		return x.Envelope
	}
	return nil
}

func (x *GetOut) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *GetOut) GetState() *Consistency {
	if x != nil {
		return x.State
	}
	return nil
}

// *
// Consistency is an opaque structure for describing the observation of consistency.  Used in cases to detect conflicts
// or catch up on passing events.
type Consistency struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// after indicates an event time coordinate.
	After         int64 `protobuf:"varint,1,opt,name=after,proto3" json:"after,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Consistency) Reset() {
	*x = Consistency{}
	mi := &file_pkg_ipc_query_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Consistency) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Consistency) ProtoMessage() {}

func (x *Consistency) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_ipc_query_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Consistency.ProtoReflect.Descriptor instead.
func (*Consistency) Descriptor() ([]byte, []int) {
	return file_pkg_ipc_query_proto_rawDescGZIP(), []int{9}
}

func (x *Consistency) GetAfter() int64 {
	if x != nil {
		return x.After
	}
	return 0
}

// *
// MaterializedEnvelope describes a particular event envelope.
type MaterializedEnvelope struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// id is the unique event ID within the system
	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// when is the service recorded timestamp of when the event in question occurred
	When *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=when,proto3" json:"when,omitempty"`
	// kind is the type of event which is represented by this ID.
	Kind          string `protobuf:"bytes,3,opt,name=kind,proto3" json:"kind,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MaterializedEnvelope) Reset() {
	*x = MaterializedEnvelope{}
	mi := &file_pkg_ipc_query_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MaterializedEnvelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MaterializedEnvelope) ProtoMessage() {}

func (x *MaterializedEnvelope) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_ipc_query_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MaterializedEnvelope.ProtoReflect.Descriptor instead.
func (*MaterializedEnvelope) Descriptor() ([]byte, []int) {
	return file_pkg_ipc_query_proto_rawDescGZIP(), []int{10}
}

func (x *MaterializedEnvelope) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *MaterializedEnvelope) GetWhen() *timestamppb.Timestamp {
	if x != nil {
		return x.When
	}
	return nil
}

func (x *MaterializedEnvelope) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

// *
// QueryIn describes the parameters and constraints for a specific query stream.
//
// A query must specify the domain and stream for selection from.  A set of clauses filter through each event within
// the query and return a tag on the QueryOut.
type QueryIn struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// *
	// events is the stream sequence to filter from.
	Events *DomainStream `protobuf:"bytes,1,opt,name=events,proto3" json:"events,omitempty"`
	// *
	// OnKindClause matches events of a specific kind, optionally with additional clauses to further filter events of
	// interest.
	OnKind []*OnKindClause `protobuf:"bytes,2,rep,name=onKind,proto3" json:"onKind,omitempty"`
	// *
	// onID describes specific IDs we are interested in retrieving.
	OnID []*OnIDClause `protobuf:"bytes,3,rep,name=onID,proto3" json:"onID,omitempty"`
	// *
	// state describes the target consistency model to use for this particular query.  Useful for repeated queries to
	// ensure all events are observed.
	State *Consistency `protobuf:"bytes,4,opt,name=state,proto3,oneof" json:"state,omitempty"`
	// *
	// onEach matches all events within the the target domain stream.
	OnEach *OnEachEvent `protobuf:"bytes,5,opt,name=onEach,proto3,oneof" json:"onEach,omitempty"`
	// *
	// afterID filters events to only those with ID greater than the specified value.
	AfterID       *int64 `protobuf:"varint,6,opt,name=afterID,proto3,oneof" json:"afterID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryIn) Reset() {
	*x = QueryIn{}
	mi := &file_pkg_ipc_query_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryIn) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryIn) ProtoMessage() {}

func (x *QueryIn) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_ipc_query_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryIn.ProtoReflect.Descriptor instead.
func (*QueryIn) Descriptor() ([]byte, []int) {
	return file_pkg_ipc_query_proto_rawDescGZIP(), []int{11}
}

func (x *QueryIn) GetEvents() *DomainStream {
	if x != nil {
		return x.Events
	}
	return nil
}

func (x *QueryIn) GetOnKind() []*OnKindClause {
	if x != nil {
		return x.OnKind
	}
	return nil
}

func (x *QueryIn) GetOnID() []*OnIDClause {
	if x != nil {
		return x.OnID
	}
	return nil
}

func (x *QueryIn) GetState() *Consistency {
	if x != nil {
		return x.State
	}
	return nil
}

func (x *QueryIn) GetOnEach() *OnEachEvent {
	if x != nil {
		return x.OnEach
	}
	return nil
}

func (x *QueryIn) GetAfterID() int64 {
	if x != nil && x.AfterID != nil {
		return *x.AfterID
	}
	return 0
}

// *
// OnKindClause configures a filter to match specific kinds of events matching additional datils.
type OnKindClause struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// kind to match within the stream
	Kind string `protobuf:"bytes,1,opt,name=kind,proto3" json:"kind,omitempty"`
	// allOp contains the tag for each event matching this kind.  allOpConfig should be set if this value is set.
	AllOp *int64 `protobuf:"varint,2,opt,name=allOp,proto3,oneof" json:"allOp,omitempty"`
	// allOpConfig describes how to return each event for matching all events.  This element has no effect if allOp is
	// not set.
	AllOpConfig *ResultInclude `protobuf:"bytes,3,opt,name=allOpConfig,proto3,oneof" json:"allOpConfig,omitempty"`
	// *
	// subsets describes interest in matching a subset of a given document against each document for return.
	Subsets       []*OnKindSubsetMatch `protobuf:"bytes,4,rep,name=subsets,proto3" json:"subsets,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OnKindClause) Reset() {
	*x = OnKindClause{}
	mi := &file_pkg_ipc_query_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OnKindClause) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OnKindClause) ProtoMessage() {}

func (x *OnKindClause) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_ipc_query_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OnKindClause.ProtoReflect.Descriptor instead.
func (*OnKindClause) Descriptor() ([]byte, []int) {
	return file_pkg_ipc_query_proto_rawDescGZIP(), []int{12}
}

func (x *OnKindClause) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *OnKindClause) GetAllOp() int64 {
	if x != nil && x.AllOp != nil {
		return *x.AllOp
	}
	return 0
}

func (x *OnKindClause) GetAllOpConfig() *ResultInclude {
	if x != nil {
		return x.AllOpConfig
	}
	return nil
}

func (x *OnKindClause) GetSubsets() []*OnKindSubsetMatch {
	if x != nil {
		return x.Subsets
	}
	return nil
}

// *
// OnKindSubsetMatch performs subset matches against the target events.
type OnKindSubsetMatch struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// *
	// match is the JSON document to match a subset of keys with exact matches with.
	Match []byte `protobuf:"bytes,1,opt,name=match,proto3" json:"match,omitempty"`
	// *
	// op is the tag to be returned
	Op int64 `protobuf:"varint,2,opt,name=op,proto3" json:"op,omitempty"`
	// *
	// style describes how each operation should be returned.
	Style         *ResultInclude `protobuf:"bytes,3,opt,name=style,proto3,oneof" json:"style,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OnKindSubsetMatch) Reset() {
	*x = OnKindSubsetMatch{}
	mi := &file_pkg_ipc_query_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OnKindSubsetMatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OnKindSubsetMatch) ProtoMessage() {}

func (x *OnKindSubsetMatch) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_ipc_query_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OnKindSubsetMatch.ProtoReflect.Descriptor instead.
func (*OnKindSubsetMatch) Descriptor() ([]byte, []int) {
	return file_pkg_ipc_query_proto_rawDescGZIP(), []int{13}
}

func (x *OnKindSubsetMatch) GetMatch() []byte {
	if x != nil {
		return x.Match
	}
	return nil
}

func (x *OnKindSubsetMatch) GetOp() int64 {
	if x != nil {
		return x.Op
	}
	return 0
}

func (x *OnKindSubsetMatch) GetStyle() *ResultInclude {
	if x != nil {
		return x.Style
	}
	return nil
}

type OnIDClause struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// id is the event ID to be retrieved
	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// op is the tag for the target handler to be returned in the result stream
	Op int64 `protobuf:"varint,2,opt,name=op,proto3" json:"op,omitempty"`
	// style details the interested data to be returned.
	Style         *ResultInclude `protobuf:"bytes,3,opt,name=style,proto3,oneof" json:"style,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OnIDClause) Reset() {
	*x = OnIDClause{}
	mi := &file_pkg_ipc_query_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OnIDClause) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OnIDClause) ProtoMessage() {}

func (x *OnIDClause) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_ipc_query_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OnIDClause.ProtoReflect.Descriptor instead.
func (*OnIDClause) Descriptor() ([]byte, []int) {
	return file_pkg_ipc_query_proto_rawDescGZIP(), []int{14}
}

func (x *OnIDClause) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *OnIDClause) GetOp() int64 {
	if x != nil {
		return x.Op
	}
	return 0
}

func (x *OnIDClause) GetStyle() *ResultInclude {
	if x != nil {
		return x.Style
	}
	return nil
}

type OnEachEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Op            int64                  `protobuf:"varint,1,opt,name=op,proto3" json:"op,omitempty"`
	Style         *ResultInclude         `protobuf:"bytes,2,opt,name=style,proto3,oneof" json:"style,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OnEachEvent) Reset() {
	*x = OnEachEvent{}
	mi := &file_pkg_ipc_query_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OnEachEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OnEachEvent) ProtoMessage() {}

func (x *OnEachEvent) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_ipc_query_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OnEachEvent.ProtoReflect.Descriptor instead.
func (*OnEachEvent) Descriptor() ([]byte, []int) {
	return file_pkg_ipc_query_proto_rawDescGZIP(), []int{15}
}

func (x *OnEachEvent) GetOp() int64 {
	if x != nil {
		return x.Op
	}
	return 0
}

func (x *OnEachEvent) GetStyle() *ResultInclude {
	if x != nil {
		return x.Style
	}
	return nil
}

// *
// QueryOut represents a single event of interest.
type QueryOut struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// *
	// op is the operation tag which matched the event.  Generally used to manage dispatching the event to an appropriate
	// handler.
	Op int64 `protobuf:"varint,1,opt,name=op,proto3" json:"op,omitempty"`
	// *
	// id is the ID of the event in question
	Id *int64 `protobuf:"varint,2,opt,name=id,proto3,oneof" json:"id,omitempty"`
	// *
	// envelope is the event for the target event in question
	Envelope *MaterializedEnvelope `protobuf:"bytes,3,opt,name=envelope,proto3,oneof" json:"envelope,omitempty"`
	// *
	// body is the JSON encoded by body of the target object.
	Body          []byte `protobuf:"bytes,4,opt,name=body,proto3,oneof" json:"body,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryOut) Reset() {
	*x = QueryOut{}
	mi := &file_pkg_ipc_query_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryOut) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryOut) ProtoMessage() {}

func (x *QueryOut) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_ipc_query_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryOut.ProtoReflect.Descriptor instead.
func (*QueryOut) Descriptor() ([]byte, []int) {
	return file_pkg_ipc_query_proto_rawDescGZIP(), []int{16}
}

func (x *QueryOut) GetOp() int64 {
	if x != nil {
		return x.Op
	}
	return 0
}

func (x *QueryOut) GetId() int64 {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return 0
}

func (x *QueryOut) GetEnvelope() *MaterializedEnvelope {
	if x != nil {
		return x.Envelope
	}
	return nil
}

func (x *QueryOut) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

// *
// ResultInclude describes how a result set should be returned.  If no value is selected then the operation tag will
// still be invoked without any additional data.  This may be useful for counting events among other reasons.
type ResultInclude struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// *
	// attaches the envelope but not the data
	Envelope *bool `protobuf:"varint,1,opt,name=envelope,proto3,oneof" json:"envelope,omitempty"`
	// *
	// body returns the JSON encoded body of the event
	Body          *bool `protobuf:"varint,2,opt,name=body,proto3,oneof" json:"body,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResultInclude) Reset() {
	*x = ResultInclude{}
	mi := &file_pkg_ipc_query_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResultInclude) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResultInclude) ProtoMessage() {}

func (x *ResultInclude) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_ipc_query_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResultInclude.ProtoReflect.Descriptor instead.
func (*ResultInclude) Descriptor() ([]byte, []int) {
	return file_pkg_ipc_query_proto_rawDescGZIP(), []int{17}
}

func (x *ResultInclude) GetEnvelope() bool {
	if x != nil && x.Envelope != nil {
		return *x.Envelope
	}
	return false
}

func (x *ResultInclude) GetBody() bool {
	if x != nil && x.Body != nil {
		return *x.Body
	}
	return false
}

type SetPositionIn struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Events        *DomainStream          `protobuf:"bytes,1,opt,name=events,proto3" json:"events,omitempty"`
	Consumer      string                 `protobuf:"bytes,2,opt,name=consumer,proto3" json:"consumer,omitempty"`
	EventID       int64                  `protobuf:"varint,3,opt,name=eventID,proto3" json:"eventID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetPositionIn) Reset() {
	*x = SetPositionIn{}
	mi := &file_pkg_ipc_query_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetPositionIn) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetPositionIn) ProtoMessage() {}

func (x *SetPositionIn) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_ipc_query_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetPositionIn.ProtoReflect.Descriptor instead.
func (*SetPositionIn) Descriptor() ([]byte, []int) {
	return file_pkg_ipc_query_proto_rawDescGZIP(), []int{18}
}

func (x *SetPositionIn) GetEvents() *DomainStream {
	if x != nil {
		return x.Events
	}
	return nil
}

func (x *SetPositionIn) GetConsumer() string {
	if x != nil {
		return x.Consumer
	}
	return ""
}

func (x *SetPositionIn) GetEventID() int64 {
	if x != nil {
		return x.EventID
	}
	return 0
}

type SetPositionOut struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Ok              bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Error           string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	CurrentEventID  int64                  `protobuf:"varint,3,opt,name=currentEventID,proto3" json:"currentEventID,omitempty"`
	PreviousEventID int64                  `protobuf:"varint,4,opt,name=previousEventID,proto3" json:"previousEventID,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *SetPositionOut) Reset() {
	*x = SetPositionOut{}
	mi := &file_pkg_ipc_query_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetPositionOut) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetPositionOut) ProtoMessage() {}

func (x *SetPositionOut) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_ipc_query_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetPositionOut.ProtoReflect.Descriptor instead.
func (*SetPositionOut) Descriptor() ([]byte, []int) {
	return file_pkg_ipc_query_proto_rawDescGZIP(), []int{19}
}

func (x *SetPositionOut) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *SetPositionOut) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *SetPositionOut) GetCurrentEventID() int64 {
	if x != nil {
		return x.CurrentEventID
	}
	return 0
}

func (x *SetPositionOut) GetPreviousEventID() int64 {
	if x != nil {
		return x.PreviousEventID
	}
	return 0
}

type GetPositionIn struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Events        *DomainStream          `protobuf:"bytes,1,opt,name=events,proto3" json:"events,omitempty"`
	Consumer      string                 `protobuf:"bytes,2,opt,name=consumer,proto3" json:"consumer,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPositionIn) Reset() {
	*x = GetPositionIn{}
	mi := &file_pkg_ipc_query_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPositionIn) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPositionIn) ProtoMessage() {}

func (x *GetPositionIn) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_ipc_query_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPositionIn.ProtoReflect.Descriptor instead.
func (*GetPositionIn) Descriptor() ([]byte, []int) {
	return file_pkg_ipc_query_proto_rawDescGZIP(), []int{20}
}

func (x *GetPositionIn) GetEvents() *DomainStream {
	if x != nil {
		return x.Events
	}
	return nil
}

func (x *GetPositionIn) GetConsumer() string {
	if x != nil {
		return x.Consumer
	}
	return ""
}

type GetPositionOut struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventID       int64                  `protobuf:"varint,1,opt,name=eventID,proto3" json:"eventID,omitempty"`
	Found         bool                   `protobuf:"varint,2,opt,name=found,proto3" json:"found,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPositionOut) Reset() {
	*x = GetPositionOut{}
	mi := &file_pkg_ipc_query_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPositionOut) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPositionOut) ProtoMessage() {}

func (x *GetPositionOut) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_ipc_query_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPositionOut.ProtoReflect.Descriptor instead.
func (*GetPositionOut) Descriptor() ([]byte, []int) {
	return file_pkg_ipc_query_proto_rawDescGZIP(), []int{21}
}

func (x *GetPositionOut) GetEventID() int64 {
	if x != nil {
		return x.EventID
	}
	return 0
}

func (x *GetPositionOut) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

type ListConsumersIn struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Events        *DomainStream          `protobuf:"bytes,1,opt,name=events,proto3" json:"events,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListConsumersIn) Reset() {
	*x = ListConsumersIn{}
	mi := &file_pkg_ipc_query_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListConsumersIn) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListConsumersIn) ProtoMessage() {}

func (x *ListConsumersIn) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_ipc_query_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListConsumersIn.ProtoReflect.Descriptor instead.
func (*ListConsumersIn) Descriptor() ([]byte, []int) {
	return file_pkg_ipc_query_proto_rawDescGZIP(), []int{22}
}

func (x *ListConsumersIn) GetEvents() *DomainStream {
	if x != nil {
		return x.Events
	}
	return nil
}

type ListConsumersOut struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Consumers     []string               `protobuf:"bytes,1,rep,name=consumers,proto3" json:"consumers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListConsumersOut) Reset() {
	*x = ListConsumersOut{}
	mi := &file_pkg_ipc_query_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListConsumersOut) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListConsumersOut) ProtoMessage() {}

func (x *ListConsumersOut) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_ipc_query_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListConsumersOut.ProtoReflect.Descriptor instead.
func (*ListConsumersOut) Descriptor() ([]byte, []int) {
	return file_pkg_ipc_query_proto_rawDescGZIP(), []int{23}
}

func (x *ListConsumersOut) GetConsumers() []string {
	if x != nil {
		return x.Consumers
	}
	return nil
}

type DeletePositionIn struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Events        *DomainStream          `protobuf:"bytes,1,opt,name=events,proto3" json:"events,omitempty"`
	Consumer      string                 `protobuf:"bytes,2,opt,name=consumer,proto3" json:"consumer,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeletePositionIn) Reset() {
	*x = DeletePositionIn{}
	mi := &file_pkg_ipc_query_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeletePositionIn) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletePositionIn) ProtoMessage() {}

func (x *DeletePositionIn) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_ipc_query_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletePositionIn.ProtoReflect.Descriptor instead.
func (*DeletePositionIn) Descriptor() ([]byte, []int) {
	return file_pkg_ipc_query_proto_rawDescGZIP(), []int{24}
}

func (x *DeletePositionIn) GetEvents() *DomainStream {
	if x != nil {
		return x.Events
	}
	return nil
}

func (x *DeletePositionIn) GetConsumer() string {
	if x != nil {
		return x.Consumer
	}
	return ""
}

type DeletePositionOut struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeletePositionOut) Reset() {
	*x = DeletePositionOut{}
	mi := &file_pkg_ipc_query_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeletePositionOut) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletePositionOut) ProtoMessage() {}

func (x *DeletePositionOut) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_ipc_query_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletePositionOut.ProtoReflect.Descriptor instead.
func (*DeletePositionOut) Descriptor() ([]byte, []int) {
	return file_pkg_ipc_query_proto_rawDescGZIP(), []int{25}
}

func (x *DeletePositionOut) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

// Lock identifies a consumer lock by consumer name and holder identity.
type Lock struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Consumer      string                 `protobuf:"bytes,1,opt,name=consumer,proto3" json:"consumer,omitempty"`
	Holder        string                 `protobuf:"bytes,2,opt,name=holder,proto3" json:"holder,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Lock) Reset() {
	*x = Lock{}
	mi := &file_pkg_ipc_query_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Lock) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Lock) ProtoMessage() {}

func (x *Lock) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_ipc_query_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Lock.ProtoReflect.Descriptor instead.
func (*Lock) Descriptor() ([]byte, []int) {
	return file_pkg_ipc_query_proto_rawDescGZIP(), []int{26}
}

func (x *Lock) GetConsumer() string {
	if x != nil {
		return x.Consumer
	}
	return ""
}

func (x *Lock) GetHolder() string {
	if x != nil {
		return x.Holder
	}
	return ""
}

type TryAcquireIn struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Events        *DomainStream          `protobuf:"bytes,1,opt,name=events,proto3" json:"events,omitempty"`
	Consumer      string                 `protobuf:"bytes,2,opt,name=consumer,proto3" json:"consumer,omitempty"`
	Holder        string                 `protobuf:"bytes,3,opt,name=holder,proto3" json:"holder,omitempty"`
	TtlSeconds    int32                  `protobuf:"varint,4,opt,name=ttl_seconds,json=ttlSeconds,proto3" json:"ttl_seconds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TryAcquireIn) Reset() {
	*x = TryAcquireIn{}
	mi := &file_pkg_ipc_query_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TryAcquireIn) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TryAcquireIn) ProtoMessage() {}

func (x *TryAcquireIn) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_ipc_query_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TryAcquireIn.ProtoReflect.Descriptor instead.
func (*TryAcquireIn) Descriptor() ([]byte, []int) {
	return file_pkg_ipc_query_proto_rawDescGZIP(), []int{27}
}

func (x *TryAcquireIn) GetEvents() *DomainStream {
	if x != nil {
		return x.Events
	}
	return nil
}

func (x *TryAcquireIn) GetConsumer() string {
	if x != nil {
		return x.Consumer
	}
	return ""
}

func (x *TryAcquireIn) GetHolder() string {
	if x != nil {
		return x.Holder
	}
	return ""
}

func (x *TryAcquireIn) GetTtlSeconds() int32 {
	if x != nil {
		return x.TtlSeconds
	}
	return 0
}

type TryAcquireOut struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Acquired       bool                   `protobuf:"varint,1,opt,name=acquired,proto3" json:"acquired,omitempty"`
	HeldBy         string                 `protobuf:"bytes,2,opt,name=held_by,json=heldBy,proto3" json:"held_by,omitempty"`
	GuaranteeUntil *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=guarantee_until,json=guaranteeUntil,proto3" json:"guarantee_until,omitempty"`
	HeldUntil      *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=held_until,json=heldUntil,proto3" json:"held_until,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *TryAcquireOut) Reset() {
	*x = TryAcquireOut{}
	mi := &file_pkg_ipc_query_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TryAcquireOut) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TryAcquireOut) ProtoMessage() {}

func (x *TryAcquireOut) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_ipc_query_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TryAcquireOut.ProtoReflect.Descriptor instead.
func (*TryAcquireOut) Descriptor() ([]byte, []int) {
	return file_pkg_ipc_query_proto_rawDescGZIP(), []int{28}
}

func (x *TryAcquireOut) GetAcquired() bool {
	if x != nil {
		return x.Acquired
	}
	return false
}

func (x *TryAcquireOut) GetHeldBy() string {
	if x != nil {
		return x.HeldBy
	}
	return ""
}

func (x *TryAcquireOut) GetGuaranteeUntil() *timestamppb.Timestamp {
	if x != nil {
		return x.GuaranteeUntil
	}
	return nil
}

func (x *TryAcquireOut) GetHeldUntil() *timestamppb.Timestamp {
	if x != nil {
		return x.HeldUntil
	}
	return nil
}

type ReleaseIn struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Events        *DomainStream          `protobuf:"bytes,1,opt,name=events,proto3" json:"events,omitempty"`
	Consumer      string                 `protobuf:"bytes,2,opt,name=consumer,proto3" json:"consumer,omitempty"`
	Holder        string                 `protobuf:"bytes,3,opt,name=holder,proto3" json:"holder,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReleaseIn) Reset() {
	*x = ReleaseIn{}
	mi := &file_pkg_ipc_query_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReleaseIn) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReleaseIn) ProtoMessage() {}

func (x *ReleaseIn) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_ipc_query_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReleaseIn.ProtoReflect.Descriptor instead.
func (*ReleaseIn) Descriptor() ([]byte, []int) {
	return file_pkg_ipc_query_proto_rawDescGZIP(), []int{29}
}

func (x *ReleaseIn) GetEvents() *DomainStream {
	if x != nil {
		return x.Events
	}
	return nil
}

func (x *ReleaseIn) GetConsumer() string {
	if x != nil {
		return x.Consumer
	}
	return ""
}

func (x *ReleaseIn) GetHolder() string {
	if x != nil {
		return x.Holder
	}
	return ""
}

type ReleaseOut struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReleaseOut) Reset() {
	*x = ReleaseOut{}
	mi := &file_pkg_ipc_query_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReleaseOut) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReleaseOut) ProtoMessage() {}

func (x *ReleaseOut) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_ipc_query_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReleaseOut.ProtoReflect.Descriptor instead.
func (*ReleaseOut) Descriptor() ([]byte, []int) {
	return file_pkg_ipc_query_proto_rawDescGZIP(), []int{30}
}

func (x *ReleaseOut) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

type ListLocksIn struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Events        *DomainStream          `protobuf:"bytes,1,opt,name=events,proto3" json:"events,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListLocksIn) Reset() {
	*x = ListLocksIn{}
	mi := &file_pkg_ipc_query_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListLocksIn) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListLocksIn) ProtoMessage() {}

func (x *ListLocksIn) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_ipc_query_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListLocksIn.ProtoReflect.Descriptor instead.
func (*ListLocksIn) Descriptor() ([]byte, []int) {
	return file_pkg_ipc_query_proto_rawDescGZIP(), []int{31}
}

func (x *ListLocksIn) GetEvents() *DomainStream {
	if x != nil {
		return x.Events
	}
	return nil
}

type ListLocksOut struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Locks         []*LockState           `protobuf:"bytes,1,rep,name=locks,proto3" json:"locks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListLocksOut) Reset() {
	*x = ListLocksOut{}
	mi := &file_pkg_ipc_query_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListLocksOut) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListLocksOut) ProtoMessage() {}

func (x *ListLocksOut) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_ipc_query_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListLocksOut.ProtoReflect.Descriptor instead.
func (*ListLocksOut) Descriptor() ([]byte, []int) {
	return file_pkg_ipc_query_proto_rawDescGZIP(), []int{32}
}

func (x *ListLocksOut) GetLocks() []*LockState {
	if x != nil {
		return x.Locks
	}
	return nil
}

type LockState struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Consumer       string                 `protobuf:"bytes,1,opt,name=consumer,proto3" json:"consumer,omitempty"`
	Domain         string                 `protobuf:"bytes,2,opt,name=domain,proto3" json:"domain,omitempty"`
	Stream         string                 `protobuf:"bytes,3,opt,name=stream,proto3" json:"stream,omitempty"`
	Holder         string                 `protobuf:"bytes,4,opt,name=holder,proto3" json:"holder,omitempty"`
	AcquiredAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=acquired_at,json=acquiredAt,proto3" json:"acquired_at,omitempty"`
	HeartbeatAt    *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=heartbeat_at,json=heartbeatAt,proto3" json:"heartbeat_at,omitempty"`
	Ttl            int32                  `protobuf:"varint,7,opt,name=ttl,proto3" json:"ttl,omitempty"`
	GuaranteeUntil *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=guarantee_until,json=guaranteeUntil,proto3" json:"guarantee_until,omitempty"`
	HeldUntil      *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=held_until,json=heldUntil,proto3" json:"held_until,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *LockState) Reset() {
	*x = LockState{}
	mi := &file_pkg_ipc_query_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LockState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LockState) ProtoMessage() {}

func (x *LockState) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_ipc_query_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LockState.ProtoReflect.Descriptor instead.
func (*LockState) Descriptor() ([]byte, []int) {
	return file_pkg_ipc_query_proto_rawDescGZIP(), []int{33}
}

func (x *LockState) GetConsumer() string {
	if x != nil {
		return x.Consumer
	}
	return ""
}

func (x *LockState) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

func (x *LockState) GetStream() string {
	if x != nil {
		return x.Stream
	}
	return ""
}

func (x *LockState) GetHolder() string {
	if x != nil {
		return x.Holder
	}
	return ""
}

func (x *LockState) GetAcquiredAt() *timestamppb.Timestamp {
	if x != nil {
		return x.AcquiredAt
	}
	return nil
}

func (x *LockState) GetHeartbeatAt() *timestamppb.Timestamp {
	if x != nil {
		return x.HeartbeatAt
	}
	return nil
}

func (x *LockState) GetTtl() int32 {
	if x != nil {
		return x.Ttl
	}
	return 0
}

func (x *LockState) GetGuaranteeUntil() *timestamppb.Timestamp {
	if x != nil {
		return x.GuaranteeUntil
	}
	return nil
}

func (x *LockState) GetHeldUntil() *timestamppb.Timestamp {
	if x != nil {
		return x.HeldUntil
	}
	return nil
}

// KeepAliveClientMessage is sent from client to server in the KeepAlive bidirectional stream.
type KeepAliveClientMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Message:
	//
	//	*KeepAliveClientMessage_Heartbeat
	//	*KeepAliveClientMessage_ReleaseRequest
	Message       isKeepAliveClientMessage_Message `protobuf_oneof:"message"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KeepAliveClientMessage) Reset() {
	*x = KeepAliveClientMessage{}
	mi := &file_pkg_ipc_query_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeepAliveClientMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeepAliveClientMessage) ProtoMessage() {}

func (x *KeepAliveClientMessage) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_ipc_query_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeepAliveClientMessage.ProtoReflect.Descriptor instead.
func (*KeepAliveClientMessage) Descriptor() ([]byte, []int) {
	return file_pkg_ipc_query_proto_rawDescGZIP(), []int{34}
}

func (x *KeepAliveClientMessage) GetMessage() isKeepAliveClientMessage_Message {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *KeepAliveClientMessage) GetHeartbeat() *KeepAliveHeartbeat {
	if x != nil {
		if x, ok := x.Message.(*KeepAliveClientMessage_Heartbeat); ok {
			return x.Heartbeat
		}
	}
	return nil
}

func (x *KeepAliveClientMessage) GetReleaseRequest() *KeepAliveReleaseRequest {
	if x != nil {
		if x, ok := x.Message.(*KeepAliveClientMessage_ReleaseRequest); ok {
			return x.ReleaseRequest
		}
	}
	return nil
}

type isKeepAliveClientMessage_Message interface {
	isKeepAliveClientMessage_Message()
}

type KeepAliveClientMessage_Heartbeat struct {
	Heartbeat *KeepAliveHeartbeat `protobuf:"bytes,1,opt,name=heartbeat,proto3,oneof"`
}

type KeepAliveClientMessage_ReleaseRequest struct {
	ReleaseRequest *KeepAliveReleaseRequest `protobuf:"bytes,2,opt,name=release_request,json=releaseRequest,proto3,oneof"`
}

func (*KeepAliveClientMessage_Heartbeat) isKeepAliveClientMessage_Message() {}

func (*KeepAliveClientMessage_ReleaseRequest) isKeepAliveClientMessage_Message() {}

type KeepAliveHeartbeat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Events        *DomainStream          `protobuf:"bytes,1,opt,name=events,proto3" json:"events,omitempty"`
	Consumer      string                 `protobuf:"bytes,2,opt,name=consumer,proto3" json:"consumer,omitempty"`
	Holder        string                 `protobuf:"bytes,3,opt,name=holder,proto3" json:"holder,omitempty"`
	Position      int64                  `protobuf:"varint,4,opt,name=position,proto3" json:"position,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KeepAliveHeartbeat) Reset() {
	*x = KeepAliveHeartbeat{}
	mi := &file_pkg_ipc_query_proto_msgTypes[35]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeepAliveHeartbeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeepAliveHeartbeat) ProtoMessage() {}

func (x *KeepAliveHeartbeat) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_ipc_query_proto_msgTypes[35]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeepAliveHeartbeat.ProtoReflect.Descriptor instead.
func (*KeepAliveHeartbeat) Descriptor() ([]byte, []int) {
	return file_pkg_ipc_query_proto_rawDescGZIP(), []int{35}
}

func (x *KeepAliveHeartbeat) GetEvents() *DomainStream {
	if x != nil {
		return x.Events
	}
	return nil
}

func (x *KeepAliveHeartbeat) GetConsumer() string {
	if x != nil {
		return x.Consumer
	}
	return ""
}

func (x *KeepAliveHeartbeat) GetHolder() string {
	if x != nil {
		return x.Holder
	}
	return ""
}

func (x *KeepAliveHeartbeat) GetPosition() int64 {
	if x != nil {
		return x.Position
	}
	return 0
}

type KeepAliveReleaseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KeepAliveReleaseRequest) Reset() {
	*x = KeepAliveReleaseRequest{}
	mi := &file_pkg_ipc_query_proto_msgTypes[36]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeepAliveReleaseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeepAliveReleaseRequest) ProtoMessage() {}

func (x *KeepAliveReleaseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_ipc_query_proto_msgTypes[36]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeepAliveReleaseRequest.ProtoReflect.Descriptor instead.
func (*KeepAliveReleaseRequest) Descriptor() ([]byte, []int) {
	return file_pkg_ipc_query_proto_rawDescGZIP(), []int{36}
}

// KeepAliveServerMessage is sent from server to client in the KeepAlive bidirectional stream.
type KeepAliveServerMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Message:
	//
	//	*KeepAliveServerMessage_LockStatus
	//	*KeepAliveServerMessage_ReleaseAck
	Message       isKeepAliveServerMessage_Message `protobuf_oneof:"message"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KeepAliveServerMessage) Reset() {
	*x = KeepAliveServerMessage{}
	mi := &file_pkg_ipc_query_proto_msgTypes[37]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeepAliveServerMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeepAliveServerMessage) ProtoMessage() {}

func (x *KeepAliveServerMessage) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_ipc_query_proto_msgTypes[37]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeepAliveServerMessage.ProtoReflect.Descriptor instead.
func (*KeepAliveServerMessage) Descriptor() ([]byte, []int) {
	return file_pkg_ipc_query_proto_rawDescGZIP(), []int{37}
}

func (x *KeepAliveServerMessage) GetMessage() isKeepAliveServerMessage_Message {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *KeepAliveServerMessage) GetLockStatus() *KeepAliveLockStatus {
	if x != nil {
		if x, ok := x.Message.(*KeepAliveServerMessage_LockStatus); ok {
			return x.LockStatus
		}
	}
	return nil
}

func (x *KeepAliveServerMessage) GetReleaseAck() *KeepAliveReleaseAck {
	if x != nil {
		if x, ok := x.Message.(*KeepAliveServerMessage_ReleaseAck); ok {
			return x.ReleaseAck
		}
	}
	return nil
}

type isKeepAliveServerMessage_Message interface {
	isKeepAliveServerMessage_Message()
}

type KeepAliveServerMessage_LockStatus struct {
	LockStatus *KeepAliveLockStatus `protobuf:"bytes,1,opt,name=lock_status,json=lockStatus,proto3,oneof"`
}

type KeepAliveServerMessage_ReleaseAck struct {
	ReleaseAck *KeepAliveReleaseAck `protobuf:"bytes,2,opt,name=release_ack,json=releaseAck,proto3,oneof"`
}

func (*KeepAliveServerMessage_LockStatus) isKeepAliveServerMessage_Message() {}

func (*KeepAliveServerMessage_ReleaseAck) isKeepAliveServerMessage_Message() {}

type KeepAliveLockStatus struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Locked         bool                   `protobuf:"varint,1,opt,name=locked,proto3" json:"locked,omitempty"`
	Reason         LockStatusReason       `protobuf:"varint,2,opt,name=reason,proto3,enum=ipc.LockStatusReason" json:"reason,omitempty"`
	GuaranteeUntil *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=guarantee_until,json=guaranteeUntil,proto3" json:"guarantee_until,omitempty"`
	HeldUntil      *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=held_until,json=heldUntil,proto3" json:"held_until,omitempty"`
	// target_version is populated only when reason = CONFLICT
	TargetVersion *int64 `protobuf:"varint,5,opt,name=target_version,json=targetVersion,proto3,oneof" json:"target_version,omitempty"`
	// current_version is populated only when reason = CONFLICT
	CurrentVersion *int64 `protobuf:"varint,6,opt,name=current_version,json=currentVersion,proto3,oneof" json:"current_version,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *KeepAliveLockStatus) Reset() {
	*x = KeepAliveLockStatus{}
	mi := &file_pkg_ipc_query_proto_msgTypes[38]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeepAliveLockStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeepAliveLockStatus) ProtoMessage() {}

func (x *KeepAliveLockStatus) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_ipc_query_proto_msgTypes[38]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeepAliveLockStatus.ProtoReflect.Descriptor instead.
func (*KeepAliveLockStatus) Descriptor() ([]byte, []int) {
	return file_pkg_ipc_query_proto_rawDescGZIP(), []int{38}
}

func (x *KeepAliveLockStatus) GetLocked() bool {
	if x != nil {
		return x.Locked
	}
	return false
}

func (x *KeepAliveLockStatus) GetReason() LockStatusReason {
	if x != nil {
		return x.Reason
	}
	return LockStatusReason_UNSPECIFIED
}

func (x *KeepAliveLockStatus) GetGuaranteeUntil() *timestamppb.Timestamp {
	if x != nil {
		return x.GuaranteeUntil
	}
	return nil
}

func (x *KeepAliveLockStatus) GetHeldUntil() *timestamppb.Timestamp {
	if x != nil {
		return x.HeldUntil
	}
	return nil
}

func (x *KeepAliveLockStatus) GetTargetVersion() int64 {
	if x != nil && x.TargetVersion != nil {
		return *x.TargetVersion
	}
	return 0
}

func (x *KeepAliveLockStatus) GetCurrentVersion() int64 {
	if x != nil && x.CurrentVersion != nil {
		return *x.CurrentVersion
	}
	return 0
}

type KeepAliveReleaseAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KeepAliveReleaseAck) Reset() {
	*x = KeepAliveReleaseAck{}
	mi := &file_pkg_ipc_query_proto_msgTypes[39]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeepAliveReleaseAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeepAliveReleaseAck) ProtoMessage() {}

func (x *KeepAliveReleaseAck) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_ipc_query_proto_msgTypes[39]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeepAliveReleaseAck.ProtoReflect.Descriptor instead.
func (*KeepAliveReleaseAck) Descriptor() ([]byte, []int) {
	return file_pkg_ipc_query_proto_rawDescGZIP(), []int{39}
}

func (x *KeepAliveReleaseAck) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

var File_pkg_ipc_query_proto protoreflect.FileDescriptor

const file_pkg_ipc_query_proto_rawDesc = "" +
	"\n" +
	"\x13pkg/ipc/query.proto\x12\x03ipc\x1a\x1fgoogle/protobuf/timestamp.proto\";\n" +
	"\x0eCreateStreamIn\x12)\n" +
	"\x06target\x18\x01 \x01(\v2\x11.ipc.DomainStreamR\x06target\"+\n" +
	"\x0fCreateStreamOut\x12\x18\n" +
	"\aexisted\x18\x01 \x01(\bR\aexisted\"\x0f\n" +
	"\rListStreamsIn\";\n" +
	"\x0eListStreamsOut\x12)\n" +
	"\x06target\x18\x01 \x03(\v2\x11.ipc.DomainStreamR\x06target\">\n" +
	"\fDomainStream\x12\x16\n" +
	"\x06domain\x18\x01 \x01(\tR\x06domain\x12\x16\n" +
	"\x06stream\x18\x02 \x01(\tR\x06stream\"\xd6\x01\n" +
	"\bSubmitIn\x12)\n" +
	"\x06events\x18\x01 \x01(\v2\x11.ipc.DomainStreamR\x06events\x12\x12\n" +
	"\x04kind\x18\x02 \x01(\tR\x04kind\x12\x12\n" +
	"\x04body\x18\x03 \x01(\fR\x04body\x129\n" +
	"\fexpectations\x18\x04 \x01(\v2\x10.ipc.ConsistencyH\x00R\fexpectations\x88\x01\x01\x12\"\n" +
	"\x04lock\x18\x05 \x01(\v2\t.ipc.LockH\x01R\x04lock\x88\x01\x01B\x0f\n" +
	"\r_expectationsB\a\n" +
	"\x05_lock\"R\n" +
	"\tSubmitOut\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12+\n" +
	"\x05state\x18\x02 \x01(\v2\x10.ipc.ConsistencyH\x00R\x05state\x88\x01\x01B\b\n" +
	"\x06_state\"\x8e\x01\n" +
	"\x05GetIn\x12)\n" +
	"\x06events\x18\x01 \x01(\v2\x11.ipc.DomainStreamR\x06events\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\x03R\x02id\x129\n" +
	"\fexpectations\x18\x04 \x01(\v2\x10.ipc.ConsistencyH\x00R\fexpectations\x88\x01\x01B\x0f\n" +
	"\r_expectations\"\x90\x01\n" +
	"\x06GetOut\x125\n" +
	"\benvelope\x18\x01 \x01(\v2\x19.ipc.MaterializedEnvelopeR\benvelope\x12\x18\n" +
	"\apayload\x18\x02 \x01(\fR\apayload\x12+\n" +
	"\x05state\x18\x03 \x01(\v2\x10.ipc.ConsistencyH\x00R\x05state\x88\x01\x01B\b\n" +
	"\x06_state\"#\n" +
	"\vConsistency\x12\x14\n" +
	"\x05after\x18\x01 \x01(\x03R\x05after\"j\n" +
	"\x14MaterializedEnvelope\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12.\n" +
	"\x04when\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\x04when\x12\x12\n" +
	"\x04kind\x18\x03 \x01(\tR\x04kind\"\xa0\x02\n" +
	"\aQueryIn\x12)\n" +
	"\x06events\x18\x01 \x01(\v2\x11.ipc.DomainStreamR\x06events\x12)\n" +
	"\x06onKind\x18\x02 \x03(\v2\x11.ipc.OnKindClauseR\x06onKind\x12#\n" +
	"\x04onID\x18\x03 \x03(\v2\x0f.ipc.OnIDClauseR\x04onID\x12+\n" +
	"\x05state\x18\x04 \x01(\v2\x10.ipc.ConsistencyH\x00R\x05state\x88\x01\x01\x12-\n" +
	"\x06onEach\x18\x05 \x01(\v2\x10.ipc.OnEachEventH\x01R\x06onEach\x88\x01\x01\x12\x1d\n" +
	"\aafterID\x18\x06 \x01(\x03H\x02R\aafterID\x88\x01\x01B\b\n" +
	"\x06_stateB\t\n" +
	"\a_onEachB\n" +
	"\n" +
	"\b_afterID\"\xc4\x01\n" +
	"\fOnKindClause\x12\x12\n" +
	"\x04kind\x18\x01 \x01(\tR\x04kind\x12\x19\n" +
	"\x05allOp\x18\x02 \x01(\x03H\x00R\x05allOp\x88\x01\x01\x129\n" +
	"\vallOpConfig\x18\x03 \x01(\v2\x12.ipc.ResultIncludeH\x01R\vallOpConfig\x88\x01\x01\x120\n" +
	"\asubsets\x18\x04 \x03(\v2\x16.ipc.OnKindSubsetMatchR\asubsetsB\b\n" +
	"\x06_allOpB\x0e\n" +
	"\f_allOpConfig\"r\n" +
	"\x11OnKindSubsetMatch\x12\x14\n" +
	"\x05match\x18\x01 \x01(\fR\x05match\x12\x0e\n" +
	"\x02op\x18\x02 \x01(\x03R\x02op\x12-\n" +
	"\x05style\x18\x03 \x01(\v2\x12.ipc.ResultIncludeH\x00R\x05style\x88\x01\x01B\b\n" +
	"\x06_style\"e\n" +
	"\n" +
	"OnIDClause\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x0e\n" +
	"\x02op\x18\x02 \x01(\x03R\x02op\x12-\n" +
	"\x05style\x18\x03 \x01(\v2\x12.ipc.ResultIncludeH\x00R\x05style\x88\x01\x01B\b\n" +
	"\x06_style\"V\n" +
	"\vOnEachEvent\x12\x0e\n" +
	"\x02op\x18\x01 \x01(\x03R\x02op\x12-\n" +
	"\x05style\x18\x02 \x01(\v2\x12.ipc.ResultIncludeH\x00R\x05style\x88\x01\x01B\b\n" +
	"\x06_style\"\xa1\x01\n" +
	"\bQueryOut\x12\x0e\n" +
	"\x02op\x18\x01 \x01(\x03R\x02op\x12\x13\n" +
	"\x02id\x18\x02 \x01(\x03H\x00R\x02id\x88\x01\x01\x12:\n" +
	"\benvelope\x18\x03 \x01(\v2\x19.ipc.MaterializedEnvelopeH\x01R\benvelope\x88\x01\x01\x12\x17\n" +
	"\x04body\x18\x04 \x01(\fH\x02R\x04body\x88\x01\x01B\x05\n" +
	"\x03_idB\v\n" +
	"\t_envelopeB\a\n" +
	"\x05_body\"_\n" +
	"\rResultInclude\x12\x1f\n" +
	"\benvelope\x18\x01 \x01(\bH\x00R\benvelope\x88\x01\x01\x12\x17\n" +
	"\x04body\x18\x02 \x01(\bH\x01R\x04body\x88\x01\x01B\v\n" +
	"\t_envelopeB\a\n" +
	"\x05_body\"p\n" +
	"\rSetPositionIn\x12)\n" +
	"\x06events\x18\x01 \x01(\v2\x11.ipc.DomainStreamR\x06events\x12\x1a\n" +
	"\bconsumer\x18\x02 \x01(\tR\bconsumer\x12\x18\n" +
	"\aeventID\x18\x03 \x01(\x03R\aeventID\"\x88\x01\n" +
	"\x0eSetPositionOut\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x12&\n" +
	"\x0ecurrentEventID\x18\x03 \x01(\x03R\x0ecurrentEventID\x12(\n" +
	"\x0fpreviousEventID\x18\x04 \x01(\x03R\x0fpreviousEventID\"V\n" +
	"\rGetPositionIn\x12)\n" +
	"\x06events\x18\x01 \x01(\v2\x11.ipc.DomainStreamR\x06events\x12\x1a\n" +
	"\bconsumer\x18\x02 \x01(\tR\bconsumer\"@\n" +
	"\x0eGetPositionOut\x12\x18\n" +
	"\aeventID\x18\x01 \x01(\x03R\aeventID\x12\x14\n" +
	"\x05found\x18\x02 \x01(\bR\x05found\"<\n" +
	"\x0fListConsumersIn\x12)\n" +
	"\x06events\x18\x01 \x01(\v2\x11.ipc.DomainStreamR\x06events\"0\n" +
	"\x10ListConsumersOut\x12\x1c\n" +
	"\tconsumers\x18\x01 \x03(\tR\tconsumers\"Y\n" +
	"\x10DeletePositionIn\x12)\n" +
	"\x06events\x18\x01 \x01(\v2\x11.ipc.DomainStreamR\x06events\x12\x1a\n" +
	"\bconsumer\x18\x02 \x01(\tR\bconsumer\"#\n" +
	"\x11DeletePositionOut\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\":\n" +
	"\x04Lock\x12\x1a\n" +
	"\bconsumer\x18\x01 \x01(\tR\bconsumer\x12\x16\n" +
	"\x06holder\x18\x02 \x01(\tR\x06holder\"\x8e\x01\n" +
	"\fTryAcquireIn\x12)\n" +
	"\x06events\x18\x01 \x01(\v2\x11.ipc.DomainStreamR\x06events\x12\x1a\n" +
	"\bconsumer\x18\x02 \x01(\tR\bconsumer\x12\x16\n" +
	"\x06holder\x18\x03 \x01(\tR\x06holder\x12\x1f\n" +
	"\vttl_seconds\x18\x04 \x01(\x05R\n" +
	"ttlSeconds\"\xc4\x01\n" +
	"\rTryAcquireOut\x12\x1a\n" +
	"\bacquired\x18\x01 \x01(\bR\bacquired\x12\x17\n" +
	"\aheld_by\x18\x02 \x01(\tR\x06heldBy\x12C\n" +
	"\x0fguarantee_until\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\x0eguaranteeUntil\x129\n" +
	"\n" +
	"held_until\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\theldUntil\"j\n" +
	"\tReleaseIn\x12)\n" +
	"\x06events\x18\x01 \x01(\v2\x11.ipc.DomainStreamR\x06events\x12\x1a\n" +
	"\bconsumer\x18\x02 \x01(\tR\bconsumer\x12\x16\n" +
	"\x06holder\x18\x03 \x01(\tR\x06holder\"\x1c\n" +
	"\n" +
	"ReleaseOut\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\"8\n" +
	"\vListLocksIn\x12)\n" +
	"\x06events\x18\x01 \x01(\v2\x11.ipc.DomainStreamR\x06events\"4\n" +
	"\fListLocksOut\x12$\n" +
	"\x05locks\x18\x01 \x03(\v2\x0e.ipc.LockStateR\x05locks\"\xfd\x02\n" +
	"\tLockState\x12\x1a\n" +
	"\bconsumer\x18\x01 \x01(\tR\bconsumer\x12\x16\n" +
	"\x06domain\x18\x02 \x01(\tR\x06domain\x12\x16\n" +
	"\x06stream\x18\x03 \x01(\tR\x06stream\x12\x16\n" +
	"\x06holder\x18\x04 \x01(\tR\x06holder\x12;\n" +
	"\vacquired_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"acquiredAt\x12=\n" +
	"\fheartbeat_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\vheartbeatAt\x12\x10\n" +
	"\x03ttl\x18\a \x01(\x05R\x03ttl\x12C\n" +
	"\x0fguarantee_until\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\x0eguaranteeUntil\x129\n" +
	"\n" +
	"held_until\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\theldUntil\"\xa5\x01\n" +
	"\x16KeepAliveClientMessage\x127\n" +
	"\theartbeat\x18\x01 \x01(\v2\x17.ipc.KeepAliveHeartbeatH\x00R\theartbeat\x12G\n" +
	"\x0frelease_request\x18\x02 \x01(\v2\x1c.ipc.KeepAliveReleaseRequestH\x00R\x0ereleaseRequestB\t\n" +
	"\amessage\"\x8f\x01\n" +
	"\x12KeepAliveHeartbeat\x12)\n" +
	"\x06events\x18\x01 \x01(\v2\x11.ipc.DomainStreamR\x06events\x12\x1a\n" +
	"\bconsumer\x18\x02 \x01(\tR\bconsumer\x12\x16\n" +
	"\x06holder\x18\x03 \x01(\tR\x06holder\x12\x1a\n" +
	"\bposition\x18\x04 \x01(\x03R\bposition\"\x19\n" +
	"\x17KeepAliveReleaseRequest\"\x9d\x01\n" +
	"\x16KeepAliveServerMessage\x12;\n" +
	"\vlock_status\x18\x01 \x01(\v2\x18.ipc.KeepAliveLockStatusH\x00R\n" +
	"lockStatus\x12;\n" +
	"\vrelease_ack\x18\x02 \x01(\v2\x18.ipc.KeepAliveReleaseAckH\x00R\n" +
	"releaseAckB\t\n" +
	"\amessage\"\xdd\x02\n" +
	"\x13KeepAliveLockStatus\x12\x16\n" +
	"\x06locked\x18\x01 \x01(\bR\x06locked\x12-\n" +
	"\x06reason\x18\x02 \x01(\x0e2\x15.ipc.LockStatusReasonR\x06reason\x12C\n" +
	"\x0fguarantee_until\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\x0eguaranteeUntil\x129\n" +
	"\n" +
	"held_until\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\theldUntil\x12*\n" +
	"\x0etarget_version\x18\x05 \x01(\x03H\x00R\rtargetVersion\x88\x01\x01\x12,\n" +
	"\x0fcurrent_version\x18\x06 \x01(\x03H\x01R\x0ecurrentVersion\x88\x01\x01B\x11\n" +
	"\x0f_target_versionB\x12\n" +
	"\x10_current_version\"%\n" +
	"\x13KeepAliveReleaseAck\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok*W\n" +
	"\x10LockStatusReason\x12\x0f\n" +
	"\vUNSPECIFIED\x10\x00\x12\v\n" +
	"\aRENEWED\x10\x01\x12\v\n" +
	"\aEXPIRED\x10\x02\x12\n" +
	"\n" +
	"\x06STOLEN\x10\x03\x12\f\n" +
	"\bCONFLICT\x10\x042m\n" +
	"\aCommand\x129\n" +
	"\fCreateStream\x12\x13.ipc.CreateStreamIn\x1a\x14.ipc.CreateStreamOut\x12'\n" +
	"\x06Submit\x12\r.ipc.SubmitIn\x1a\x0e.ipc.SubmitOut2\xaf\x01\n" +
	"\x05Query\x126\n" +
	"\vListStreams\x12\x12.ipc.ListStreamsIn\x1a\x13.ipc.ListStreamsOut\x12\x1e\n" +
	"\x03Get\x12\n" +
	".ipc.GetIn\x1a\v.ipc.GetOut\x12&\n" +
	"\x05Query\x12\f.ipc.QueryIn\x1a\r.ipc.QueryOut0\x01\x12&\n" +
	"\x05Watch\x12\f.ipc.QueryIn\x1a\r.ipc.QueryOut0\x012\x81\x02\n" +
	"\x10ConsumerPosition\x126\n" +
	"\vSetPosition\x12\x12.ipc.SetPositionIn\x1a\x13.ipc.SetPositionOut\x126\n" +
	"\vGetPosition\x12\x12.ipc.GetPositionIn\x1a\x13.ipc.GetPositionOut\x12<\n" +
	"\rListConsumers\x12\x14.ipc.ListConsumersIn\x1a\x15.ipc.ListConsumersOut\x12?\n" +
	"\x0eDeletePosition\x12\x15.ipc.DeletePositionIn\x1a\x16.ipc.DeletePositionOut2\xec\x01\n" +
	"\fConsumerLock\x123\n" +
	"\n" +
	"TryAcquire\x12\x11.ipc.TryAcquireIn\x1a\x12.ipc.TryAcquireOut\x12*\n" +
	"\aRelease\x12\x0e.ipc.ReleaseIn\x1a\x0f.ipc.ReleaseOut\x12I\n" +
	"\tKeepAlive\x12\x1b.ipc.KeepAliveClientMessage\x1a\x1b.ipc.KeepAliveServerMessage(\x010\x01\x120\n" +
	"\tListLocks\x12\x10.ipc.ListLocksIn\x1a\x11.ipc.ListLocksOutB\tZ\apkg/ipcb\x06proto3"

var (
	file_pkg_ipc_query_proto_rawDescOnce sync.Once
	file_pkg_ipc_query_proto_rawDescData []byte
)

func file_pkg_ipc_query_proto_rawDescGZIP() []byte {
	file_pkg_ipc_query_proto_rawDescOnce.Do(func() {
		file_pkg_ipc_query_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_ipc_query_proto_rawDesc), len(file_pkg_ipc_query_proto_rawDesc)))
	})
	return file_pkg_ipc_query_proto_rawDescData
}

var file_pkg_ipc_query_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_pkg_ipc_query_proto_msgTypes = make([]protoimpl.MessageInfo, 40)
var file_pkg_ipc_query_proto_goTypes = []any{
	(LockStatusReason)(0),           // 0: ipc.LockStatusReason
	(*CreateStreamIn)(nil),          // 1: ipc.CreateStreamIn
	(*CreateStreamOut)(nil),         // 2: ipc.CreateStreamOut
	(*ListStreamsIn)(nil),           // 3: ipc.ListStreamsIn
	(*ListStreamsOut)(nil),          // 4: ipc.ListStreamsOut
	(*DomainStream)(nil),            // 5: ipc.DomainStream
	(*SubmitIn)(nil),                // 6: ipc.SubmitIn
	(*SubmitOut)(nil),               // 7: ipc.SubmitOut
	(*GetIn)(nil),                   // 8: ipc.GetIn
	(*GetOut)(nil),                  // 9: ipc.GetOut
	(*Consistency)(nil),             // 10: ipc.Consistency
	(*MaterializedEnvelope)(nil),    // 11: ipc.MaterializedEnvelope
	(*QueryIn)(nil),                 // 12: ipc.QueryIn
	(*OnKindClause)(nil),            // 13: ipc.OnKindClause
	(*OnKindSubsetMatch)(nil),       // 14: ipc.OnKindSubsetMatch
	(*OnIDClause)(nil),              // 15: ipc.OnIDClause
	(*OnEachEvent)(nil),             // 16: ipc.OnEachEvent
	(*QueryOut)(nil),                // 17: ipc.QueryOut
	(*ResultInclude)(nil),           // 18: ipc.ResultInclude
	(*SetPositionIn)(nil),           // 19: ipc.SetPositionIn
	(*SetPositionOut)(nil),          // 20: ipc.SetPositionOut
	(*GetPositionIn)(nil),           // 21: ipc.GetPositionIn
	(*GetPositionOut)(nil),          // 22: ipc.GetPositionOut
	(*ListConsumersIn)(nil),         // 23: ipc.ListConsumersIn
	(*ListConsumersOut)(nil),        // 24: ipc.ListConsumersOut
	(*DeletePositionIn)(nil),        // 25: ipc.DeletePositionIn
	(*DeletePositionOut)(nil),       // 26: ipc.DeletePositionOut
	(*Lock)(nil),                    // 27: ipc.Lock
	(*TryAcquireIn)(nil),            // 28: ipc.TryAcquireIn
	(*TryAcquireOut)(nil),           // 29: ipc.TryAcquireOut
	(*ReleaseIn)(nil),               // 30: ipc.ReleaseIn
	(*ReleaseOut)(nil),              // 31: ipc.ReleaseOut
	(*ListLocksIn)(nil),             // 32: ipc.ListLocksIn
	(*ListLocksOut)(nil),            // 33: ipc.ListLocksOut
	(*LockState)(nil),               // 34: ipc.LockState
	(*KeepAliveClientMessage)(nil),  // 35: ipc.KeepAliveClientMessage
	(*KeepAliveHeartbeat)(nil),      // 36: ipc.KeepAliveHeartbeat
	(*KeepAliveReleaseRequest)(nil), // 37: ipc.KeepAliveReleaseRequest
	(*KeepAliveServerMessage)(nil),  // 38: ipc.KeepAliveServerMessage
	(*KeepAliveLockStatus)(nil),     // 39: ipc.KeepAliveLockStatus
	(*KeepAliveReleaseAck)(nil),     // 40: ipc.KeepAliveReleaseAck
	(*timestamppb.Timestamp)(nil),   // 41: google.protobuf.Timestamp
}
var file_pkg_ipc_query_proto_depIdxs = []int32{
	5,  // 0: ipc.CreateStreamIn.target:type_name -> ipc.DomainStream
	5,  // 1: ipc.ListStreamsOut.target:type_name -> ipc.DomainStream
	5,  // 2: ipc.SubmitIn.events:type_name -> ipc.DomainStream
	10, // 3: ipc.SubmitIn.expectations:type_name -> ipc.Consistency
	27, // 4: ipc.SubmitIn.lock:type_name -> ipc.Lock
	10, // 5: ipc.SubmitOut.state:type_name -> ipc.Consistency
	5,  // 6: ipc.GetIn.events:type_name -> ipc.DomainStream
	10, // 7: ipc.GetIn.expectations:type_name -> ipc.Consistency
	11, // 8: ipc.GetOut.envelope:type_name -> ipc.MaterializedEnvelope
	10, // 9: ipc.GetOut.state:type_name -> ipc.Consistency
	41, // 10: ipc.MaterializedEnvelope.when:type_name -> google.protobuf.Timestamp
	5,  // 11: ipc.QueryIn.events:type_name -> ipc.DomainStream
	13, // 12: ipc.QueryIn.onKind:type_name -> ipc.OnKindClause
	15, // 13: ipc.QueryIn.onID:type_name -> ipc.OnIDClause
	10, // 14: ipc.QueryIn.state:type_name -> ipc.Consistency
	16, // 15: ipc.QueryIn.onEach:type_name -> ipc.OnEachEvent
	18, // 16: ipc.OnKindClause.allOpConfig:type_name -> ipc.ResultInclude
	14, // 17: ipc.OnKindClause.subsets:type_name -> ipc.OnKindSubsetMatch
	18, // 18: ipc.OnKindSubsetMatch.style:type_name -> ipc.ResultInclude
	18, // 19: ipc.OnIDClause.style:type_name -> ipc.ResultInclude
	18, // 20: ipc.OnEachEvent.style:type_name -> ipc.ResultInclude
	11, // 21: ipc.QueryOut.envelope:type_name -> ipc.MaterializedEnvelope
	5,  // 22: ipc.SetPositionIn.events:type_name -> ipc.DomainStream
	5,  // 23: ipc.GetPositionIn.events:type_name -> ipc.DomainStream
	5,  // 24: ipc.ListConsumersIn.events:type_name -> ipc.DomainStream
	5,  // 25: ipc.DeletePositionIn.events:type_name -> ipc.DomainStream
	5,  // 26: ipc.TryAcquireIn.events:type_name -> ipc.DomainStream
	41, // 27: ipc.TryAcquireOut.guarantee_until:type_name -> google.protobuf.Timestamp
	41, // 28: ipc.TryAcquireOut.held_until:type_name -> google.protobuf.Timestamp
	5,  // 29: ipc.ReleaseIn.events:type_name -> ipc.DomainStream
	5,  // 30: ipc.ListLocksIn.events:type_name -> ipc.DomainStream
	34, // 31: ipc.ListLocksOut.locks:type_name -> ipc.LockState
	41, // 32: ipc.LockState.acquired_at:type_name -> google.protobuf.Timestamp
	41, // 33: ipc.LockState.heartbeat_at:type_name -> google.protobuf.Timestamp
	41, // 34: ipc.LockState.guarantee_until:type_name -> google.protobuf.Timestamp
	41, // 35: ipc.LockState.held_until:type_name -> google.protobuf.Timestamp
	36, // 36: ipc.KeepAliveClientMessage.heartbeat:type_name -> ipc.KeepAliveHeartbeat
	37, // 37: ipc.KeepAliveClientMessage.release_request:type_name -> ipc.KeepAliveReleaseRequest
	5,  // 38: ipc.KeepAliveHeartbeat.events:type_name -> ipc.DomainStream
	39, // 39: ipc.KeepAliveServerMessage.lock_status:type_name -> ipc.KeepAliveLockStatus
	40, // 40: ipc.KeepAliveServerMessage.release_ack:type_name -> ipc.KeepAliveReleaseAck
	0,  // 41: ipc.KeepAliveLockStatus.reason:type_name -> ipc.LockStatusReason
	41, // 42: ipc.KeepAliveLockStatus.guarantee_until:type_name -> google.protobuf.Timestamp
	41, // 43: ipc.KeepAliveLockStatus.held_until:type_name -> google.protobuf.Timestamp
	1,  // 44: ipc.Command.CreateStream:input_type -> ipc.CreateStreamIn
	6,  // 45: ipc.Command.Submit:input_type -> ipc.SubmitIn
	3,  // 46: ipc.Query.ListStreams:input_type -> ipc.ListStreamsIn
	8,  // 47: ipc.Query.Get:input_type -> ipc.GetIn
	12, // 48: ipc.Query.Query:input_type -> ipc.QueryIn
	12, // 49: ipc.Query.Watch:input_type -> ipc.QueryIn
	19, // 50: ipc.ConsumerPosition.SetPosition:input_type -> ipc.SetPositionIn
	21, // 51: ipc.ConsumerPosition.GetPosition:input_type -> ipc.GetPositionIn
	23, // 52: ipc.ConsumerPosition.ListConsumers:input_type -> ipc.ListConsumersIn
	25, // 53: ipc.ConsumerPosition.DeletePosition:input_type -> ipc.DeletePositionIn
	28, // 54: ipc.ConsumerLock.TryAcquire:input_type -> ipc.TryAcquireIn
	30, // 55: ipc.ConsumerLock.Release:input_type -> ipc.ReleaseIn
	35, // 56: ipc.ConsumerLock.KeepAlive:input_type -> ipc.KeepAliveClientMessage
	32, // 57: ipc.ConsumerLock.ListLocks:input_type -> ipc.ListLocksIn
	2,  // 58: ipc.Command.CreateStream:output_type -> ipc.CreateStreamOut
	7,  // 59: ipc.Command.Submit:output_type -> ipc.SubmitOut
	4,  // 60: ipc.Query.ListStreams:output_type -> ipc.ListStreamsOut
	9,  // 61: ipc.Query.Get:output_type -> ipc.GetOut
	17, // 62: ipc.Query.Query:output_type -> ipc.QueryOut
	17, // 63: ipc.Query.Watch:output_type -> ipc.QueryOut
	20, // 64: ipc.ConsumerPosition.SetPosition:output_type -> ipc.SetPositionOut
	22, // 65: ipc.ConsumerPosition.GetPosition:output_type -> ipc.GetPositionOut
	24, // 66: ipc.ConsumerPosition.ListConsumers:output_type -> ipc.ListConsumersOut
	26, // 67: ipc.ConsumerPosition.DeletePosition:output_type -> ipc.DeletePositionOut
	29, // 68: ipc.ConsumerLock.TryAcquire:output_type -> ipc.TryAcquireOut
	31, // 69: ipc.ConsumerLock.Release:output_type -> ipc.ReleaseOut
	38, // 70: ipc.ConsumerLock.KeepAlive:output_type -> ipc.KeepAliveServerMessage
	33, // 71: ipc.ConsumerLock.ListLocks:output_type -> ipc.ListLocksOut
	58, // [58:72] is the sub-list for method output_type
	44, // [44:58] is the sub-list for method input_type
	44, // [44:44] is the sub-list for extension type_name
	44, // [44:44] is the sub-list for extension extendee
	0,  // [0:44] is the sub-list for field type_name
}

func init() { file_pkg_ipc_query_proto_init() }
func file_pkg_ipc_query_proto_init() {
	if File_pkg_ipc_query_proto != nil {
		return
	}
	file_pkg_ipc_query_proto_msgTypes[5].OneofWrappers = []any{}
	file_pkg_ipc_query_proto_msgTypes[6].OneofWrappers = []any{}
	file_pkg_ipc_query_proto_msgTypes[7].OneofWrappers = []any{}
	file_pkg_ipc_query_proto_msgTypes[8].OneofWrappers = []any{}
	file_pkg_ipc_query_proto_msgTypes[11].OneofWrappers = []any{}
	file_pkg_ipc_query_proto_msgTypes[12].OneofWrappers = []any{}
	file_pkg_ipc_query_proto_msgTypes[13].OneofWrappers = []any{}
	file_pkg_ipc_query_proto_msgTypes[14].OneofWrappers = []any{}
	file_pkg_ipc_query_proto_msgTypes[15].OneofWrappers = []any{}
	file_pkg_ipc_query_proto_msgTypes[16].OneofWrappers = []any{}
	file_pkg_ipc_query_proto_msgTypes[17].OneofWrappers = []any{}
	file_pkg_ipc_query_proto_msgTypes[34].OneofWrappers = []any{
		(*KeepAliveClientMessage_Heartbeat)(nil),
		(*KeepAliveClientMessage_ReleaseRequest)(nil),
	}
	file_pkg_ipc_query_proto_msgTypes[37].OneofWrappers = []any{
		(*KeepAliveServerMessage_LockStatus)(nil),
		(*KeepAliveServerMessage_ReleaseAck)(nil),
	}
	file_pkg_ipc_query_proto_msgTypes[38].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_ipc_query_proto_rawDesc), len(file_pkg_ipc_query_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   40,
			NumExtensions: 0,
			NumServices:   4,
		},
		GoTypes:           file_pkg_ipc_query_proto_goTypes,
		DependencyIndexes: file_pkg_ipc_query_proto_depIdxs,
		EnumInfos:         file_pkg_ipc_query_proto_enumTypes,
		MessageInfos:      file_pkg_ipc_query_proto_msgTypes,
	}.Build()
	File_pkg_ipc_query_proto = out.File
	file_pkg_ipc_query_proto_goTypes = nil
	file_pkg_ipc_query_proto_depIdxs = nil
}
