image:
  tag: "59f0dfc"

volumeMounts:
  - name: config
    mountPath: "/secrets"
    readOnly: true
volumes:
  - name: config
    secret:
      secretName: service-config
      optional: false

env:
  - name: ENV
    value: prod
  - name: OTEL_EXPORTER
    value: jaeger
  - name: OTEL_SERVICE_NAME
    value: pgcqrs
  - name: JAEGER_ENDPOINT
    value: http://jaeger.platform-jaeger.svc.workshop.k8s:14268/api/traces
  - name: CFG_PRIMARY
    value: /secrets/primary.json
