apiVersion: v1
kind: Service
metadata:
  name: {{ include "pgcqrs.fullname" . }}
  labels:
    {{- include "pgcqrs.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "pgcqrs.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "pgcqrs.fullname" . }}-grpc
  labels:
    {{- include "pgcqrs.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: grpc
      protocol: TCP
      name: grpc
  selector:
    {{- include "pgcqrs.selectorLabels" . | nindent 4 }}