// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.1
// source: pkg/indexer/views/grpc/views.proto

package grpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ViewProjectionStore_ApplyMutations_FullMethodName = "/views.ViewProjectionStore/ApplyMutations"
	ViewProjectionStore_GetEntity_FullMethodName      = "/views.ViewProjectionStore/GetEntity"
)

// ViewProjectionStoreClient is the client API for ViewProjectionStore service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ViewProjectionStore provides KV storage for view projections.
// Used by the Pump (in the developer's process) for mutations and previous-state reads.
type ViewProjectionStoreClient interface {
	ApplyMutations(ctx context.Context, in *ApplyMutationsRequest, opts ...grpc.CallOption) (*ApplyMutationsResponse, error)
	GetEntity(ctx context.Context, in *GetEntityRequest, opts ...grpc.CallOption) (*GetEntityResponse, error)
}

type viewProjectionStoreClient struct {
	cc grpc.ClientConnInterface
}

func NewViewProjectionStoreClient(cc grpc.ClientConnInterface) ViewProjectionStoreClient {
	return &viewProjectionStoreClient{cc}
}

func (c *viewProjectionStoreClient) ApplyMutations(ctx context.Context, in *ApplyMutationsRequest, opts ...grpc.CallOption) (*ApplyMutationsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApplyMutationsResponse)
	err := c.cc.Invoke(ctx, ViewProjectionStore_ApplyMutations_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *viewProjectionStoreClient) GetEntity(ctx context.Context, in *GetEntityRequest, opts ...grpc.CallOption) (*GetEntityResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetEntityResponse)
	err := c.cc.Invoke(ctx, ViewProjectionStore_GetEntity_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ViewProjectionStoreServer is the server API for ViewProjectionStore service.
// All implementations must embed UnimplementedViewProjectionStoreServer
// for forward compatibility.
//
// ViewProjectionStore provides KV storage for view projections.
// Used by the Pump (in the developer's process) for mutations and previous-state reads.
type ViewProjectionStoreServer interface {
	ApplyMutations(context.Context, *ApplyMutationsRequest) (*ApplyMutationsResponse, error)
	GetEntity(context.Context, *GetEntityRequest) (*GetEntityResponse, error)
	mustEmbedUnimplementedViewProjectionStoreServer()
}

// UnimplementedViewProjectionStoreServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedViewProjectionStoreServer struct{}

func (UnimplementedViewProjectionStoreServer) ApplyMutations(context.Context, *ApplyMutationsRequest) (*ApplyMutationsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ApplyMutations not implemented")
}
func (UnimplementedViewProjectionStoreServer) GetEntity(context.Context, *GetEntityRequest) (*GetEntityResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetEntity not implemented")
}
func (UnimplementedViewProjectionStoreServer) mustEmbedUnimplementedViewProjectionStoreServer() {}
func (UnimplementedViewProjectionStoreServer) testEmbeddedByValue()                             {}

// UnsafeViewProjectionStoreServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ViewProjectionStoreServer will
// result in compilation errors.
type UnsafeViewProjectionStoreServer interface {
	mustEmbedUnimplementedViewProjectionStoreServer()
}

func RegisterViewProjectionStoreServer(s grpc.ServiceRegistrar, srv ViewProjectionStoreServer) {
	// If the following call panics, it indicates UnimplementedViewProjectionStoreServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ViewProjectionStore_ServiceDesc, srv)
}

func _ViewProjectionStore_ApplyMutations_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ApplyMutationsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ViewProjectionStoreServer).ApplyMutations(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ViewProjectionStore_ApplyMutations_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ViewProjectionStoreServer).ApplyMutations(ctx, req.(*ApplyMutationsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ViewProjectionStore_GetEntity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetEntityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ViewProjectionStoreServer).GetEntity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ViewProjectionStore_GetEntity_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ViewProjectionStoreServer).GetEntity(ctx, req.(*GetEntityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ViewProjectionStore_ServiceDesc is the grpc.ServiceDesc for ViewProjectionStore service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ViewProjectionStore_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "views.ViewProjectionStore",
	HandlerType: (*ViewProjectionStoreServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ApplyMutations",
			Handler:    _ViewProjectionStore_ApplyMutations_Handler,
		},
		{
			MethodName: "GetEntity",
			Handler:    _ViewProjectionStore_GetEntity_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pkg/indexer/views/grpc/views.proto",
}

const (
	ViewProjectionConsumer_GetEntity_FullMethodName    = "/views.ViewProjectionConsumer/GetEntity"
	ViewProjectionConsumer_GetVersion_FullMethodName   = "/views.ViewProjectionConsumer/GetVersion"
	ViewProjectionConsumer_WatchChanges_FullMethodName = "/views.ViewProjectionConsumer/WatchChanges"
)

// ViewProjectionConsumerClient is the client API for ViewProjectionConsumer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ViewProjectionConsumer serves entity state to remote clients (webapps, downstream indexers).
type ViewProjectionConsumerClient interface {
	GetEntity(ctx context.Context, in *GetEntityRequest, opts ...grpc.CallOption) (*GetEntityResponse, error)
	GetVersion(ctx context.Context, in *GetVersionRequest, opts ...grpc.CallOption) (*GetVersionResponse, error)
	WatchChanges(ctx context.Context, in *WatchChangesRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[WatchChangesResponse], error)
}

type viewProjectionConsumerClient struct {
	cc grpc.ClientConnInterface
}

func NewViewProjectionConsumerClient(cc grpc.ClientConnInterface) ViewProjectionConsumerClient {
	return &viewProjectionConsumerClient{cc}
}

func (c *viewProjectionConsumerClient) GetEntity(ctx context.Context, in *GetEntityRequest, opts ...grpc.CallOption) (*GetEntityResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetEntityResponse)
	err := c.cc.Invoke(ctx, ViewProjectionConsumer_GetEntity_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *viewProjectionConsumerClient) GetVersion(ctx context.Context, in *GetVersionRequest, opts ...grpc.CallOption) (*GetVersionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetVersionResponse)
	err := c.cc.Invoke(ctx, ViewProjectionConsumer_GetVersion_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *viewProjectionConsumerClient) WatchChanges(ctx context.Context, in *WatchChangesRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[WatchChangesResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ViewProjectionConsumer_ServiceDesc.Streams[0], ViewProjectionConsumer_WatchChanges_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[WatchChangesRequest, WatchChangesResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ViewProjectionConsumer_WatchChangesClient = grpc.ServerStreamingClient[WatchChangesResponse]

// ViewProjectionConsumerServer is the server API for ViewProjectionConsumer service.
// All implementations must embed UnimplementedViewProjectionConsumerServer
// for forward compatibility.
//
// ViewProjectionConsumer serves entity state to remote clients (webapps, downstream indexers).
type ViewProjectionConsumerServer interface {
	GetEntity(context.Context, *GetEntityRequest) (*GetEntityResponse, error)
	GetVersion(context.Context, *GetVersionRequest) (*GetVersionResponse, error)
	WatchChanges(*WatchChangesRequest, grpc.ServerStreamingServer[WatchChangesResponse]) error
	mustEmbedUnimplementedViewProjectionConsumerServer()
}

// UnimplementedViewProjectionConsumerServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedViewProjectionConsumerServer struct{}

func (UnimplementedViewProjectionConsumerServer) GetEntity(context.Context, *GetEntityRequest) (*GetEntityResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetEntity not implemented")
}
func (UnimplementedViewProjectionConsumerServer) GetVersion(context.Context, *GetVersionRequest) (*GetVersionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetVersion not implemented")
}
func (UnimplementedViewProjectionConsumerServer) WatchChanges(*WatchChangesRequest, grpc.ServerStreamingServer[WatchChangesResponse]) error {
	return status.Error(codes.Unimplemented, "method WatchChanges not implemented")
}
func (UnimplementedViewProjectionConsumerServer) mustEmbedUnimplementedViewProjectionConsumerServer() {
}
func (UnimplementedViewProjectionConsumerServer) testEmbeddedByValue() {}

// UnsafeViewProjectionConsumerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ViewProjectionConsumerServer will
// result in compilation errors.
type UnsafeViewProjectionConsumerServer interface {
	mustEmbedUnimplementedViewProjectionConsumerServer()
}

func RegisterViewProjectionConsumerServer(s grpc.ServiceRegistrar, srv ViewProjectionConsumerServer) {
	// If the following call panics, it indicates UnimplementedViewProjectionConsumerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ViewProjectionConsumer_ServiceDesc, srv)
}

func _ViewProjectionConsumer_GetEntity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetEntityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ViewProjectionConsumerServer).GetEntity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ViewProjectionConsumer_GetEntity_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ViewProjectionConsumerServer).GetEntity(ctx, req.(*GetEntityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ViewProjectionConsumer_GetVersion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetVersionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ViewProjectionConsumerServer).GetVersion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ViewProjectionConsumer_GetVersion_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ViewProjectionConsumerServer).GetVersion(ctx, req.(*GetVersionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ViewProjectionConsumer_WatchChanges_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(WatchChangesRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ViewProjectionConsumerServer).WatchChanges(m, &grpc.GenericServerStream[WatchChangesRequest, WatchChangesResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ViewProjectionConsumer_WatchChangesServer = grpc.ServerStreamingServer[WatchChangesResponse]

// ViewProjectionConsumer_ServiceDesc is the grpc.ServiceDesc for ViewProjectionConsumer service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ViewProjectionConsumer_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "views.ViewProjectionConsumer",
	HandlerType: (*ViewProjectionConsumerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetEntity",
			Handler:    _ViewProjectionConsumer_GetEntity_Handler,
		},
		{
			MethodName: "GetVersion",
			Handler:    _ViewProjectionConsumer_GetVersion_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "WatchChanges",
			Handler:       _ViewProjectionConsumer_WatchChanges_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "pkg/indexer/views/grpc/views.proto",
}
