// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.35.1
// source: pkg/indexer/views/grpc/views.proto

package grpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// GetStatus reports how a GetEntity was resolved.
type GetStatus int32

const (
	GetStatus_GET_STATUS_OK        GetStatus = 0
	GetStatus_GET_STATUS_NOT_FOUND GetStatus = 1
	GetStatus_GET_STATUS_STALE     GetStatus = 2
	GetStatus_GET_STATUS_TIMEOUT   GetStatus = 3
)

// Enum value maps for GetStatus.
var (
	GetStatus_name = map[int32]string{
		0: "GET_STATUS_OK",
		1: "GET_STATUS_NOT_FOUND",
		2: "GET_STATUS_STALE",
		3: "GET_STATUS_TIMEOUT",
	}
	GetStatus_value = map[string]int32{
		"GET_STATUS_OK":        0,
		"GET_STATUS_NOT_FOUND": 1,
		"GET_STATUS_STALE":     2,
		"GET_STATUS_TIMEOUT":   3,
	}
)

func (x GetStatus) Enum() *GetStatus {
	p := new(GetStatus)
	*p = x
	return p
}

func (x GetStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GetStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_pkg_indexer_views_grpc_views_proto_enumTypes[0].Descriptor()
}

func (GetStatus) Type() protoreflect.EnumType {
	return &file_pkg_indexer_views_grpc_views_proto_enumTypes[0]
}

func (x GetStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GetStatus.Descriptor instead.
func (GetStatus) EnumDescriptor() ([]byte, []int) {
	return file_pkg_indexer_views_grpc_views_proto_rawDescGZIP(), []int{0}
}

type ApplyMutationsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Projection    string                 `protobuf:"bytes,1,opt,name=projection,proto3" json:"projection,omitempty"`
	Upserts       []*Upsert              `protobuf:"bytes,2,rep,name=upserts,proto3" json:"upserts,omitempty"`
	Deletes       []*Delete              `protobuf:"bytes,3,rep,name=deletes,proto3" json:"deletes,omitempty"`
	EventId       int64                  `protobuf:"varint,4,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	Domain        string                 `protobuf:"bytes,5,opt,name=domain,proto3" json:"domain,omitempty"`
	Stream        string                 `protobuf:"bytes,6,opt,name=stream,proto3" json:"stream,omitempty"`
	Consumer      string                 `protobuf:"bytes,7,opt,name=consumer,proto3" json:"consumer,omitempty"` // optional; defaults to projection if empty
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApplyMutationsRequest) Reset() {
	*x = ApplyMutationsRequest{}
	mi := &file_pkg_indexer_views_grpc_views_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplyMutationsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplyMutationsRequest) ProtoMessage() {}

func (x *ApplyMutationsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_indexer_views_grpc_views_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplyMutationsRequest.ProtoReflect.Descriptor instead.
func (*ApplyMutationsRequest) Descriptor() ([]byte, []int) {
	return file_pkg_indexer_views_grpc_views_proto_rawDescGZIP(), []int{0}
}

func (x *ApplyMutationsRequest) GetProjection() string {
	if x != nil {
		return x.Projection
	}
	return ""
}

func (x *ApplyMutationsRequest) GetUpserts() []*Upsert {
	if x != nil {
		return x.Upserts
	}
	return nil
}

func (x *ApplyMutationsRequest) GetDeletes() []*Delete {
	if x != nil {
		return x.Deletes
	}
	return nil
}

func (x *ApplyMutationsRequest) GetEventId() int64 {
	if x != nil {
		return x.EventId
	}
	return 0
}

func (x *ApplyMutationsRequest) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

func (x *ApplyMutationsRequest) GetStream() string {
	if x != nil {
		return x.Stream
	}
	return ""
}

func (x *ApplyMutationsRequest) GetConsumer() string {
	if x != nil {
		return x.Consumer
	}
	return ""
}

type ApplyMutationsResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	AppliedUpserts []*Upsert              `protobuf:"bytes,1,rep,name=applied_upserts,json=appliedUpserts,proto3" json:"applied_upserts,omitempty"`
	AppliedDeletes []*Delete              `protobuf:"bytes,2,rep,name=applied_deletes,json=appliedDeletes,proto3" json:"applied_deletes,omitempty"`
	Version        int64                  `protobuf:"varint,3,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ApplyMutationsResponse) Reset() {
	*x = ApplyMutationsResponse{}
	mi := &file_pkg_indexer_views_grpc_views_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplyMutationsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplyMutationsResponse) ProtoMessage() {}

func (x *ApplyMutationsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_indexer_views_grpc_views_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplyMutationsResponse.ProtoReflect.Descriptor instead.
func (*ApplyMutationsResponse) Descriptor() ([]byte, []int) {
	return file_pkg_indexer_views_grpc_views_proto_rawDescGZIP(), []int{1}
}

func (x *ApplyMutationsResponse) GetAppliedUpserts() []*Upsert {
	if x != nil {
		return x.AppliedUpserts
	}
	return nil
}

func (x *ApplyMutationsResponse) GetAppliedDeletes() []*Delete {
	if x != nil {
		return x.AppliedDeletes
	}
	return nil
}

func (x *ApplyMutationsResponse) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

type Entity struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Kind          string                 `protobuf:"bytes,1,opt,name=kind,proto3" json:"kind,omitempty"`
	Key           []string               `protobuf:"bytes,2,rep,name=key,proto3" json:"key,omitempty"`
	Value         []byte                 `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	Version       int64                  `protobuf:"varint,4,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Entity) Reset() {
	*x = Entity{}
	mi := &file_pkg_indexer_views_grpc_views_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Entity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Entity) ProtoMessage() {}

func (x *Entity) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_indexer_views_grpc_views_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Entity.ProtoReflect.Descriptor instead.
func (*Entity) Descriptor() ([]byte, []int) {
	return file_pkg_indexer_views_grpc_views_proto_rawDescGZIP(), []int{2}
}

func (x *Entity) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *Entity) GetKey() []string {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *Entity) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *Entity) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

type Upsert struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Kind          string                 `protobuf:"bytes,1,opt,name=kind,proto3" json:"kind,omitempty"`
	Key           []string               `protobuf:"bytes,2,rep,name=key,proto3" json:"key,omitempty"`
	Value         []byte                 `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	Version       int64                  `protobuf:"varint,4,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Upsert) Reset() {
	*x = Upsert{}
	mi := &file_pkg_indexer_views_grpc_views_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Upsert) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Upsert) ProtoMessage() {}

func (x *Upsert) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_indexer_views_grpc_views_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Upsert.ProtoReflect.Descriptor instead.
func (*Upsert) Descriptor() ([]byte, []int) {
	return file_pkg_indexer_views_grpc_views_proto_rawDescGZIP(), []int{3}
}

func (x *Upsert) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *Upsert) GetKey() []string {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *Upsert) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *Upsert) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

type Delete struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Kind          string                 `protobuf:"bytes,1,opt,name=kind,proto3" json:"kind,omitempty"`
	Key           []string               `protobuf:"bytes,2,rep,name=key,proto3" json:"key,omitempty"`
	Version       int64                  `protobuf:"varint,3,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Delete) Reset() {
	*x = Delete{}
	mi := &file_pkg_indexer_views_grpc_views_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Delete) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Delete) ProtoMessage() {}

func (x *Delete) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_indexer_views_grpc_views_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Delete.ProtoReflect.Descriptor instead.
func (*Delete) Descriptor() ([]byte, []int) {
	return file_pkg_indexer_views_grpc_views_proto_rawDescGZIP(), []int{4}
}

func (x *Delete) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *Delete) GetKey() []string {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *Delete) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

type AfterConstraint struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       int64                  `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AfterConstraint) Reset() {
	*x = AfterConstraint{}
	mi := &file_pkg_indexer_views_grpc_views_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AfterConstraint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AfterConstraint) ProtoMessage() {}

func (x *AfterConstraint) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_indexer_views_grpc_views_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AfterConstraint.ProtoReflect.Descriptor instead.
func (*AfterConstraint) Descriptor() ([]byte, []int) {
	return file_pkg_indexer_views_grpc_views_proto_rawDescGZIP(), []int{5}
}

func (x *AfterConstraint) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

type UntilVersionConstraint struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       int64                  `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	TimeoutMs     int64                  `protobuf:"varint,2,opt,name=timeout_ms,json=timeoutMs,proto3" json:"timeout_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UntilVersionConstraint) Reset() {
	*x = UntilVersionConstraint{}
	mi := &file_pkg_indexer_views_grpc_views_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UntilVersionConstraint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UntilVersionConstraint) ProtoMessage() {}

func (x *UntilVersionConstraint) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_indexer_views_grpc_views_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UntilVersionConstraint.ProtoReflect.Descriptor instead.
func (*UntilVersionConstraint) Descriptor() ([]byte, []int) {
	return file_pkg_indexer_views_grpc_views_proto_rawDescGZIP(), []int{6}
}

func (x *UntilVersionConstraint) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *UntilVersionConstraint) GetTimeoutMs() int64 {
	if x != nil {
		return x.TimeoutMs
	}
	return 0
}

// StoreGetEntityRequest is the plain entity read used by the write-path service.
// It intentionally carries no version constraints: ViewProjectionStore is the
// Pump's storage backend and must never wait on version. Constrained reads are
// served by ViewProjectionConsumer.GetEntity.
type StoreGetEntityRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Projection    string                 `protobuf:"bytes,1,opt,name=projection,proto3" json:"projection,omitempty"`
	Kind          string                 `protobuf:"bytes,2,opt,name=kind,proto3" json:"kind,omitempty"`
	Key           []string               `protobuf:"bytes,3,rep,name=key,proto3" json:"key,omitempty"`
	Domain        string                 `protobuf:"bytes,4,opt,name=domain,proto3" json:"domain,omitempty"`
	Stream        string                 `protobuf:"bytes,5,opt,name=stream,proto3" json:"stream,omitempty"`
	Consumer      string                 `protobuf:"bytes,6,opt,name=consumer,proto3" json:"consumer,omitempty"` // optional; defaults to projection if empty
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StoreGetEntityRequest) Reset() {
	*x = StoreGetEntityRequest{}
	mi := &file_pkg_indexer_views_grpc_views_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StoreGetEntityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoreGetEntityRequest) ProtoMessage() {}

func (x *StoreGetEntityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_indexer_views_grpc_views_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoreGetEntityRequest.ProtoReflect.Descriptor instead.
func (*StoreGetEntityRequest) Descriptor() ([]byte, []int) {
	return file_pkg_indexer_views_grpc_views_proto_rawDescGZIP(), []int{7}
}

func (x *StoreGetEntityRequest) GetProjection() string {
	if x != nil {
		return x.Projection
	}
	return ""
}

func (x *StoreGetEntityRequest) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *StoreGetEntityRequest) GetKey() []string {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *StoreGetEntityRequest) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

func (x *StoreGetEntityRequest) GetStream() string {
	if x != nil {
		return x.Stream
	}
	return ""
}

func (x *StoreGetEntityRequest) GetConsumer() string {
	if x != nil {
		return x.Consumer
	}
	return ""
}

type GetEntityRequest struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	Projection string                 `protobuf:"bytes,1,opt,name=projection,proto3" json:"projection,omitempty"`
	Kind       string                 `protobuf:"bytes,2,opt,name=kind,proto3" json:"kind,omitempty"`
	Key        []string               `protobuf:"bytes,3,rep,name=key,proto3" json:"key,omitempty"`
	// Types that are valid to be assigned to VersionConstraint:
	//
	//	*GetEntityRequest_After
	//	*GetEntityRequest_UntilVersion
	VersionConstraint isGetEntityRequest_VersionConstraint `protobuf_oneof:"version_constraint"`
	Domain            string                               `protobuf:"bytes,6,opt,name=domain,proto3" json:"domain,omitempty"`
	Stream            string                               `protobuf:"bytes,7,opt,name=stream,proto3" json:"stream,omitempty"`
	Consumer          string                               `protobuf:"bytes,8,opt,name=consumer,proto3" json:"consumer,omitempty"` // optional; defaults to projection if empty
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *GetEntityRequest) Reset() {
	*x = GetEntityRequest{}
	mi := &file_pkg_indexer_views_grpc_views_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEntityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEntityRequest) ProtoMessage() {}

func (x *GetEntityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_indexer_views_grpc_views_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEntityRequest.ProtoReflect.Descriptor instead.
func (*GetEntityRequest) Descriptor() ([]byte, []int) {
	return file_pkg_indexer_views_grpc_views_proto_rawDescGZIP(), []int{8}
}

func (x *GetEntityRequest) GetProjection() string {
	if x != nil {
		return x.Projection
	}
	return ""
}

func (x *GetEntityRequest) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *GetEntityRequest) GetKey() []string {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *GetEntityRequest) GetVersionConstraint() isGetEntityRequest_VersionConstraint {
	if x != nil {
		return x.VersionConstraint
	}
	return nil
}

func (x *GetEntityRequest) GetAfter() *AfterConstraint {
	if x != nil {
		if x, ok := x.VersionConstraint.(*GetEntityRequest_After); ok {
			return x.After
		}
	}
	return nil
}

func (x *GetEntityRequest) GetUntilVersion() *UntilVersionConstraint {
	if x != nil {
		if x, ok := x.VersionConstraint.(*GetEntityRequest_UntilVersion); ok {
			return x.UntilVersion
		}
	}
	return nil
}

func (x *GetEntityRequest) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

func (x *GetEntityRequest) GetStream() string {
	if x != nil {
		return x.Stream
	}
	return ""
}

func (x *GetEntityRequest) GetConsumer() string {
	if x != nil {
		return x.Consumer
	}
	return ""
}

type isGetEntityRequest_VersionConstraint interface {
	isGetEntityRequest_VersionConstraint()
}

type GetEntityRequest_After struct {
	After *AfterConstraint `protobuf:"bytes,4,opt,name=after,proto3,oneof"`
}

type GetEntityRequest_UntilVersion struct {
	UntilVersion *UntilVersionConstraint `protobuf:"bytes,5,opt,name=until_version,json=untilVersion,proto3,oneof"`
}

func (*GetEntityRequest_After) isGetEntityRequest_VersionConstraint() {}

func (*GetEntityRequest_UntilVersion) isGetEntityRequest_VersionConstraint() {}

type GetEntityResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entity        *Entity                `protobuf:"bytes,1,opt,name=entity,proto3" json:"entity,omitempty"`
	Status        GetStatus              `protobuf:"varint,2,opt,name=status,proto3,enum=views.GetStatus" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEntityResponse) Reset() {
	*x = GetEntityResponse{}
	mi := &file_pkg_indexer_views_grpc_views_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEntityResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEntityResponse) ProtoMessage() {}

func (x *GetEntityResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_indexer_views_grpc_views_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEntityResponse.ProtoReflect.Descriptor instead.
func (*GetEntityResponse) Descriptor() ([]byte, []int) {
	return file_pkg_indexer_views_grpc_views_proto_rawDescGZIP(), []int{9}
}

func (x *GetEntityResponse) GetEntity() *Entity {
	if x != nil {
		return x.Entity
	}
	return nil
}

func (x *GetEntityResponse) GetStatus() GetStatus {
	if x != nil {
		return x.Status
	}
	return GetStatus_GET_STATUS_OK
}

type VersionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Projection    string                 `protobuf:"bytes,1,opt,name=projection,proto3" json:"projection,omitempty"`
	Domain        string                 `protobuf:"bytes,2,opt,name=domain,proto3" json:"domain,omitempty"`
	Stream        string                 `protobuf:"bytes,3,opt,name=stream,proto3" json:"stream,omitempty"`
	Consumer      string                 `protobuf:"bytes,4,opt,name=consumer,proto3" json:"consumer,omitempty"` // optional; defaults to projection if empty
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VersionRequest) Reset() {
	*x = VersionRequest{}
	mi := &file_pkg_indexer_views_grpc_views_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VersionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VersionRequest) ProtoMessage() {}

func (x *VersionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_indexer_views_grpc_views_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VersionRequest.ProtoReflect.Descriptor instead.
func (*VersionRequest) Descriptor() ([]byte, []int) {
	return file_pkg_indexer_views_grpc_views_proto_rawDescGZIP(), []int{10}
}

func (x *VersionRequest) GetProjection() string {
	if x != nil {
		return x.Projection
	}
	return ""
}

func (x *VersionRequest) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

func (x *VersionRequest) GetStream() string {
	if x != nil {
		return x.Stream
	}
	return ""
}

func (x *VersionRequest) GetConsumer() string {
	if x != nil {
		return x.Consumer
	}
	return ""
}

type VersionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       int64                  `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VersionResponse) Reset() {
	*x = VersionResponse{}
	mi := &file_pkg_indexer_views_grpc_views_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VersionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VersionResponse) ProtoMessage() {}

func (x *VersionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_indexer_views_grpc_views_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VersionResponse.ProtoReflect.Descriptor instead.
func (*VersionResponse) Descriptor() ([]byte, []int) {
	return file_pkg_indexer_views_grpc_views_proto_rawDescGZIP(), []int{11}
}

func (x *VersionResponse) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

type WatchChangesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Projection    string                 `protobuf:"bytes,1,opt,name=projection,proto3" json:"projection,omitempty"`
	AfterVersion  *AfterConstraint       `protobuf:"bytes,2,opt,name=after_version,json=afterVersion,proto3" json:"after_version,omitempty"`
	Domain        string                 `protobuf:"bytes,3,opt,name=domain,proto3" json:"domain,omitempty"`
	Stream        string                 `protobuf:"bytes,4,opt,name=stream,proto3" json:"stream,omitempty"`
	Consumer      string                 `protobuf:"bytes,5,opt,name=consumer,proto3" json:"consumer,omitempty"` // optional; defaults to projection if empty
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchChangesRequest) Reset() {
	*x = WatchChangesRequest{}
	mi := &file_pkg_indexer_views_grpc_views_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchChangesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchChangesRequest) ProtoMessage() {}

func (x *WatchChangesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_indexer_views_grpc_views_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchChangesRequest.ProtoReflect.Descriptor instead.
func (*WatchChangesRequest) Descriptor() ([]byte, []int) {
	return file_pkg_indexer_views_grpc_views_proto_rawDescGZIP(), []int{12}
}

func (x *WatchChangesRequest) GetProjection() string {
	if x != nil {
		return x.Projection
	}
	return ""
}

func (x *WatchChangesRequest) GetAfterVersion() *AfterConstraint {
	if x != nil {
		return x.AfterVersion
	}
	return nil
}

func (x *WatchChangesRequest) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

func (x *WatchChangesRequest) GetStream() string {
	if x != nil {
		return x.Stream
	}
	return ""
}

func (x *WatchChangesRequest) GetConsumer() string {
	if x != nil {
		return x.Consumer
	}
	return ""
}

type WatchChangesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Upserts       []*Upsert              `protobuf:"bytes,1,rep,name=upserts,proto3" json:"upserts,omitempty"`
	Deletes       []*Delete              `protobuf:"bytes,2,rep,name=deletes,proto3" json:"deletes,omitempty"`
	Version       int64                  `protobuf:"varint,3,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchChangesResponse) Reset() {
	*x = WatchChangesResponse{}
	mi := &file_pkg_indexer_views_grpc_views_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchChangesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchChangesResponse) ProtoMessage() {}

func (x *WatchChangesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_indexer_views_grpc_views_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchChangesResponse.ProtoReflect.Descriptor instead.
func (*WatchChangesResponse) Descriptor() ([]byte, []int) {
	return file_pkg_indexer_views_grpc_views_proto_rawDescGZIP(), []int{13}
}

func (x *WatchChangesResponse) GetUpserts() []*Upsert {
	if x != nil {
		return x.Upserts
	}
	return nil
}

func (x *WatchChangesResponse) GetDeletes() []*Delete {
	if x != nil {
		return x.Deletes
	}
	return nil
}

func (x *WatchChangesResponse) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

var File_pkg_indexer_views_grpc_views_proto protoreflect.FileDescriptor

const file_pkg_indexer_views_grpc_views_proto_rawDesc = "" +
	"\n" +
	"\"pkg/indexer/views/grpc/views.proto\x12\x05views\"\xf0\x01\n" +
	"\x15ApplyMutationsRequest\x12\x1e\n" +
	"\n" +
	"projection\x18\x01 \x01(\tR\n" +
	"projection\x12'\n" +
	"\aupserts\x18\x02 \x03(\v2\r.views.UpsertR\aupserts\x12'\n" +
	"\adeletes\x18\x03 \x03(\v2\r.views.DeleteR\adeletes\x12\x19\n" +
	"\bevent_id\x18\x04 \x01(\x03R\aeventId\x12\x16\n" +
	"\x06domain\x18\x05 \x01(\tR\x06domain\x12\x16\n" +
	"\x06stream\x18\x06 \x01(\tR\x06stream\x12\x1a\n" +
	"\bconsumer\x18\a \x01(\tR\bconsumer\"\xa2\x01\n" +
	"\x16ApplyMutationsResponse\x126\n" +
	"\x0fapplied_upserts\x18\x01 \x03(\v2\r.views.UpsertR\x0eappliedUpserts\x126\n" +
	"\x0fapplied_deletes\x18\x02 \x03(\v2\r.views.DeleteR\x0eappliedDeletes\x12\x18\n" +
	"\aversion\x18\x03 \x01(\x03R\aversion\"^\n" +
	"\x06Entity\x12\x12\n" +
	"\x04kind\x18\x01 \x01(\tR\x04kind\x12\x10\n" +
	"\x03key\x18\x02 \x03(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x03 \x01(\fR\x05value\x12\x18\n" +
	"\aversion\x18\x04 \x01(\x03R\aversion\"^\n" +
	"\x06Upsert\x12\x12\n" +
	"\x04kind\x18\x01 \x01(\tR\x04kind\x12\x10\n" +
	"\x03key\x18\x02 \x03(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x03 \x01(\fR\x05value\x12\x18\n" +
	"\aversion\x18\x04 \x01(\x03R\aversion\"H\n" +
	"\x06Delete\x12\x12\n" +
	"\x04kind\x18\x01 \x01(\tR\x04kind\x12\x10\n" +
	"\x03key\x18\x02 \x03(\tR\x03key\x12\x18\n" +
	"\aversion\x18\x03 \x01(\x03R\aversion\"+\n" +
	"\x0fAfterConstraint\x12\x18\n" +
	"\aversion\x18\x01 \x01(\x03R\aversion\"Q\n" +
	"\x16UntilVersionConstraint\x12\x18\n" +
	"\aversion\x18\x01 \x01(\x03R\aversion\x12\x1d\n" +
	"\n" +
	"timeout_ms\x18\x02 \x01(\x03R\ttimeoutMs\"\xa9\x01\n" +
	"\x15StoreGetEntityRequest\x12\x1e\n" +
	"\n" +
	"projection\x18\x01 \x01(\tR\n" +
	"projection\x12\x12\n" +
	"\x04kind\x18\x02 \x01(\tR\x04kind\x12\x10\n" +
	"\x03key\x18\x03 \x03(\tR\x03key\x12\x16\n" +
	"\x06domain\x18\x04 \x01(\tR\x06domain\x12\x16\n" +
	"\x06stream\x18\x05 \x01(\tR\x06stream\x12\x1a\n" +
	"\bconsumer\x18\x06 \x01(\tR\bconsumer\"\xb0\x02\n" +
	"\x10GetEntityRequest\x12\x1e\n" +
	"\n" +
	"projection\x18\x01 \x01(\tR\n" +
	"projection\x12\x12\n" +
	"\x04kind\x18\x02 \x01(\tR\x04kind\x12\x10\n" +
	"\x03key\x18\x03 \x03(\tR\x03key\x12.\n" +
	"\x05after\x18\x04 \x01(\v2\x16.views.AfterConstraintH\x00R\x05after\x12D\n" +
	"\runtil_version\x18\x05 \x01(\v2\x1d.views.UntilVersionConstraintH\x00R\funtilVersion\x12\x16\n" +
	"\x06domain\x18\x06 \x01(\tR\x06domain\x12\x16\n" +
	"\x06stream\x18\a \x01(\tR\x06stream\x12\x1a\n" +
	"\bconsumer\x18\b \x01(\tR\bconsumerB\x14\n" +
	"\x12version_constraint\"d\n" +
	"\x11GetEntityResponse\x12%\n" +
	"\x06entity\x18\x01 \x01(\v2\r.views.EntityR\x06entity\x12(\n" +
	"\x06status\x18\x02 \x01(\x0e2\x10.views.GetStatusR\x06status\"|\n" +
	"\x0eVersionRequest\x12\x1e\n" +
	"\n" +
	"projection\x18\x01 \x01(\tR\n" +
	"projection\x12\x16\n" +
	"\x06domain\x18\x02 \x01(\tR\x06domain\x12\x16\n" +
	"\x06stream\x18\x03 \x01(\tR\x06stream\x12\x1a\n" +
	"\bconsumer\x18\x04 \x01(\tR\bconsumer\"+\n" +
	"\x0fVersionResponse\x12\x18\n" +
	"\aversion\x18\x01 \x01(\x03R\aversion\"\xbe\x01\n" +
	"\x13WatchChangesRequest\x12\x1e\n" +
	"\n" +
	"projection\x18\x01 \x01(\tR\n" +
	"projection\x12;\n" +
	"\rafter_version\x18\x02 \x01(\v2\x16.views.AfterConstraintR\fafterVersion\x12\x16\n" +
	"\x06domain\x18\x03 \x01(\tR\x06domain\x12\x16\n" +
	"\x06stream\x18\x04 \x01(\tR\x06stream\x12\x1a\n" +
	"\bconsumer\x18\x05 \x01(\tR\bconsumer\"\x82\x01\n" +
	"\x14WatchChangesResponse\x12'\n" +
	"\aupserts\x18\x01 \x03(\v2\r.views.UpsertR\aupserts\x12'\n" +
	"\adeletes\x18\x02 \x03(\v2\r.views.DeleteR\adeletes\x12\x18\n" +
	"\aversion\x18\x03 \x01(\x03R\aversion*f\n" +
	"\tGetStatus\x12\x11\n" +
	"\rGET_STATUS_OK\x10\x00\x12\x18\n" +
	"\x14GET_STATUS_NOT_FOUND\x10\x01\x12\x14\n" +
	"\x10GET_STATUS_STALE\x10\x02\x12\x16\n" +
	"\x12GET_STATUS_TIMEOUT\x10\x032\xa9\x01\n" +
	"\x13ViewProjectionStore\x12M\n" +
	"\x0eApplyMutations\x12\x1c.views.ApplyMutationsRequest\x1a\x1d.views.ApplyMutationsResponse\x12C\n" +
	"\tGetEntity\x12\x1c.views.StoreGetEntityRequest\x1a\x18.views.GetEntityResponse2\xdd\x01\n" +
	"\x16ViewProjectionConsumer\x12>\n" +
	"\tGetEntity\x12\x17.views.GetEntityRequest\x1a\x18.views.GetEntityResponse\x128\n" +
	"\aVersion\x12\x15.views.VersionRequest\x1a\x16.views.VersionResponse\x12I\n" +
	"\fWatchChanges\x12\x1a.views.WatchChangesRequest\x1a\x1b.views.WatchChangesResponse0\x01B4Z2github.com/meschbach/pgcqrs/pkg/indexer/views/grpcb\x06proto3"

var (
	file_pkg_indexer_views_grpc_views_proto_rawDescOnce sync.Once
	file_pkg_indexer_views_grpc_views_proto_rawDescData []byte
)

func file_pkg_indexer_views_grpc_views_proto_rawDescGZIP() []byte {
	file_pkg_indexer_views_grpc_views_proto_rawDescOnce.Do(func() {
		file_pkg_indexer_views_grpc_views_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_indexer_views_grpc_views_proto_rawDesc), len(file_pkg_indexer_views_grpc_views_proto_rawDesc)))
	})
	return file_pkg_indexer_views_grpc_views_proto_rawDescData
}

var file_pkg_indexer_views_grpc_views_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_pkg_indexer_views_grpc_views_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_pkg_indexer_views_grpc_views_proto_goTypes = []any{
	(GetStatus)(0),                 // 0: views.GetStatus
	(*ApplyMutationsRequest)(nil),  // 1: views.ApplyMutationsRequest
	(*ApplyMutationsResponse)(nil), // 2: views.ApplyMutationsResponse
	(*Entity)(nil),                 // 3: views.Entity
	(*Upsert)(nil),                 // 4: views.Upsert
	(*Delete)(nil),                 // 5: views.Delete
	(*AfterConstraint)(nil),        // 6: views.AfterConstraint
	(*UntilVersionConstraint)(nil), // 7: views.UntilVersionConstraint
	(*StoreGetEntityRequest)(nil),  // 8: views.StoreGetEntityRequest
	(*GetEntityRequest)(nil),       // 9: views.GetEntityRequest
	(*GetEntityResponse)(nil),      // 10: views.GetEntityResponse
	(*VersionRequest)(nil),         // 11: views.VersionRequest
	(*VersionResponse)(nil),        // 12: views.VersionResponse
	(*WatchChangesRequest)(nil),    // 13: views.WatchChangesRequest
	(*WatchChangesResponse)(nil),   // 14: views.WatchChangesResponse
}
var file_pkg_indexer_views_grpc_views_proto_depIdxs = []int32{
	4,  // 0: views.ApplyMutationsRequest.upserts:type_name -> views.Upsert
	5,  // 1: views.ApplyMutationsRequest.deletes:type_name -> views.Delete
	4,  // 2: views.ApplyMutationsResponse.applied_upserts:type_name -> views.Upsert
	5,  // 3: views.ApplyMutationsResponse.applied_deletes:type_name -> views.Delete
	6,  // 4: views.GetEntityRequest.after:type_name -> views.AfterConstraint
	7,  // 5: views.GetEntityRequest.until_version:type_name -> views.UntilVersionConstraint
	3,  // 6: views.GetEntityResponse.entity:type_name -> views.Entity
	0,  // 7: views.GetEntityResponse.status:type_name -> views.GetStatus
	6,  // 8: views.WatchChangesRequest.after_version:type_name -> views.AfterConstraint
	4,  // 9: views.WatchChangesResponse.upserts:type_name -> views.Upsert
	5,  // 10: views.WatchChangesResponse.deletes:type_name -> views.Delete
	1,  // 11: views.ViewProjectionStore.ApplyMutations:input_type -> views.ApplyMutationsRequest
	8,  // 12: views.ViewProjectionStore.GetEntity:input_type -> views.StoreGetEntityRequest
	9,  // 13: views.ViewProjectionConsumer.GetEntity:input_type -> views.GetEntityRequest
	11, // 14: views.ViewProjectionConsumer.Version:input_type -> views.VersionRequest
	13, // 15: views.ViewProjectionConsumer.WatchChanges:input_type -> views.WatchChangesRequest
	2,  // 16: views.ViewProjectionStore.ApplyMutations:output_type -> views.ApplyMutationsResponse
	10, // 17: views.ViewProjectionStore.GetEntity:output_type -> views.GetEntityResponse
	10, // 18: views.ViewProjectionConsumer.GetEntity:output_type -> views.GetEntityResponse
	12, // 19: views.ViewProjectionConsumer.Version:output_type -> views.VersionResponse
	14, // 20: views.ViewProjectionConsumer.WatchChanges:output_type -> views.WatchChangesResponse
	16, // [16:21] is the sub-list for method output_type
	11, // [11:16] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_pkg_indexer_views_grpc_views_proto_init() }
func file_pkg_indexer_views_grpc_views_proto_init() {
	if File_pkg_indexer_views_grpc_views_proto != nil {
		return
	}
	file_pkg_indexer_views_grpc_views_proto_msgTypes[8].OneofWrappers = []any{
		(*GetEntityRequest_After)(nil),
		(*GetEntityRequest_UntilVersion)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_indexer_views_grpc_views_proto_rawDesc), len(file_pkg_indexer_views_grpc_views_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_pkg_indexer_views_grpc_views_proto_goTypes,
		DependencyIndexes: file_pkg_indexer_views_grpc_views_proto_depIdxs,
		EnumInfos:         file_pkg_indexer_views_grpc_views_proto_enumTypes,
		MessageInfos:      file_pkg_indexer_views_grpc_views_proto_msgTypes,
	}.Build()
	File_pkg_indexer_views_grpc_views_proto = out.File
	file_pkg_indexer_views_grpc_views_proto_goTypes = nil
	file_pkg_indexer_views_grpc_views_proto_depIdxs = nil
}
