name: Go

on: [push]

jobs:
  tests:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    strategy:
      matrix:
        go-version: [ '1.21', '1.22' ]

    steps:
      - uses: actions/checkout@v4
      - name: Setup Go ${{ matrix.go-version }}
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
      # You can test your matrix by printing the current Go version
      - name: Build and run unit tests ${{ matrix.go-version }}
        run: |
          ./build.sh
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Run integration tests
        run: |
          docker run --name pg -e POSTGRES_PASSWORD=mysecretpassword --detach postgres
          CFG_PRIMARY=$PWD/deploy/integration-tests/primary.json ./migrator primary
          CFG_PRIMARY=$PWD/deploy/integration-tests/primary.json ./integration-tests.sh
  system_tests:
    runs-on: ubuntu-latest
    needs: [unit_tests]
    if: github.triggering_actor == 'meschbach' &&  github.ref == 'refs/heads/testing-container'
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4
      - name: "Setup Environment"
        run: |
          echo "BRANCH=${GITHUB_REF##*/}" >> $GITHUB_ENV
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push migrator
        uses: docker/build-push-action@v5
        with:
          platforms: "linux/amd64,linux/arm64"
          file: cmd/migrator/Dockerfile
          push: false
          tags: 'meschbach/pgcqrs-migrator:${{ env.BRANCH }}'
          load: true
      - name: Build and push service
        uses: docker/build-push-action@v5
        with:
          platforms: "linux/amd64,linux/arm64"
          file: cmd/service/Dockerfile
          push: false
          tags: 'meschbach/pgcqrs:${{ env.BRANCH }}'
          load: true

      - name: Test
        run: |
          #TODO: would this be better as a Docker Compose setup?
          docker run --name pg -e POSTGRES_PASSWORD=mysecretpassword --detach postgres
          docker run --rm  --volume $PWD/deploy/integration-tests:/secrets 'meschbach/pgcqrs-migrator:${{ env.BRANCH }}' primary
          docker run --detach --publish 9000:9000 --publish 9001:9001  --volume $PWD/deploy/integration-tests:/secrets 'meschbach/pgcqrs:${{ env.BRANCH }}'

          export PGCQRS_TEST_TRANSPORT="memory"
          export PGCQRS_TEST_URL="http://localhost:9000"
          export PGCQRS_TEST_APP_BASE="systest-"
          go test -count=1 --timeout 5s ./systest/...

          export PGCQRS_TEST_URL="http://localhost:9000"
          export PGCQRS_TEST_APP_BASE="systest-"
          go test -count=1 --timeout 5s ./systest/...

          export PGCQRS_TEST_TRANSPORT="grpc"
          export PGCQRS_TEST_URL="localhost:9001"
          export PGCQRS_TEST_APP_BASE="systest-"
          go test -count=1 --timeout 5s ./systest/...
